### ISSUE TITLE
Tux has no "pick-up-and-carry" sprite

### ISSUE THREAD

**Issue by SecularSteve** [SuperTux/supertux#1997] opened 2021-12-20 18:04 UTC
**SuperTux version:** SuperTux 0.6.2.
**System information:** Windows 10

##### Expected behavior

For there to be a "carry" sprite whenever Tux picks up a Snail or Mr. Ice Block.

##### Actual behavior

Other than the enemy going behind Tux when you grab them, his sprites are the same as if he has none.

##### Steps to reproduce actual behavior

Just pick up any enemy that can be carried, and see for yourself.

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I verified this isn't an issue that's already been reported.
- [x] This report only includes details about **one** (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [x] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [x] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by mrkubax10** [comment] 2021-12-20 18:48
Duplicate of #977

**Closed by mrkubax10** 2021-12-20 18:48 UTC
