### ISSUE TITLE
Lanterns (or magic blocks) do not work

### ISSUE THREAD

**Issue by christ2go** [SuperTux/supertux#835] opened 2018-06-09 08:07 UTC
**SuperTux version:** 0.5.1 / newest master
Light and magic blocks do not work like they are supposed to, after some time the lanterns fall through the light blocks. Furthermore light blocks sometimes just change the radius in which they display light.
##### Steps to reproduce actual behavior
Play the Level Light and Magic. Jump onto the red lantern, wait for it to fall down.
##### Additional debugging information
This bug was introduced somewhere between 0.4.0 and 0.5.0.

**Comment by busybody42** [comment] 2018-06-10 21:49
Also, this is similar to a bug in Fiona's world with "color cave" and the color blocks do not become solid when the ambient light is the same color!

**Comment by weluvgoatz** [comment] 2018-07-05 14:36
i have also come across this bug. i cannot complete light and magic now.

**Comment by weluvgoatz** [comment] 2019-12-05 17:29
I believe this has been fixed.

**Comment by brmbrmcar** [comment] 2020-05-23 05:37
I can confirm it has not been fixed.

**Comment by Zwatotem** [comment] 2020-07-17 23:22
Is this fixed now, as #1465 has been merged?

**Comment by Semphriss** [comment] 2020-12-04 20:04
I'm assuming no one reproduced the error since #1465, therefore I'm closing this issue.

If the error happens again, please open a **new** issue, as re-opening this one could go unnoticed. (This issue is too old to be actively monitored)

**Closed by Semphriss** 2020-12-04 20:04 UTC
Labels: type:bug
