### ISSUE TITLE
Pausing during object-induced sounds cuts off the sound playing

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#2099] opened 2022-01-15 14:45 UTC
v0.6.3
win10

When you jump on an enemy, or collect a coin, or burn haybales, whatever object interaction - most things produce a sound with it. However, if you pause during this sound playing, and then unpause, the sound wont continue playing.

Try jumping on a haywire or bomb. Then simply pause, and the sound will be gone. This is particularly noticeable for haywires, but it actually happens for every object noise, like a chain of haybales burning or even a snowball being squished (although some are very short to really notice - still happens).

**Comment by Vankata453** [comment] 2022-01-15 14:53
I have also noticed the same happening with the sound, that plays right after you get the start powerup.

**Comment by Semphriss** [comment] 2022-01-15 17:43
Duplicate of #1391 ?

**Comment by Alasdairbugs** [comment] 2022-01-15 17:50
i forgor

**Closed** 2022-01-15 18:37 UTC
