### ISSUE TITLE
Problem with saved files

### ISSUE THREAD

**Issue by spider2016** [SuperTux/supertux#199] opened 2015-10-24 09:11 UTC
Officialy supertux0.3.5a-1.fc22   from  Russian fedora 22 is not working.
Additional levels not saved too at HDD
Do you speak Russian?, I very poor speak english!

**Comment by spider2016** [comment] 2015-10-24 09:15
Old  compiled (Janury 2015compiled with git and cmake)supertux2 worked fine! That is why problem with supertux0.3.5a-1.fc22 version

**Comment by brmbrmcar** [comment] 2015-10-24 09:18
We'll have to look into it.

**Comment by brmbrmcar** [comment] 2015-10-24 09:24
It doesn't work at all?

**Comment by spider2016** [comment] 2015-10-24 09:27
May be do you speake russian))?  i am very long speak english.

**Comment by maxteufel** [comment] 2015-10-24 09:27
>  Russian fedora 22

Is this some kind of Fedora spinoff or is it just Fedora with Russian localization?

> Do you speak Russian?, I very poor speak english!

There's no contributor speaking Russian as far as I know, official support is provided in English.

> Additional levels not saved too at HDD

Well, sorry, but we'd actually need more information to debug this. Do you have write permission to `~/.supertux2`? Pastebin stdout? Can you provide an strace?

**Comment by spider2016** [comment] 2015-10-24 09:29
yes, this directory ~supertux is exist. I can give you archive with this directory

**Comment by spider2016** [comment] 2015-10-24 09:30
I began level again after exit, from first level

**Comment by maxteufel** [comment] 2015-10-24 09:31
No I don't want an archive (fwiw, `~supertux` would be the home directory of the user `supertux` in bash). I want to know what permission the directory and its contents have.

**Comment by maxteufel** [comment] 2015-10-24 09:32
> I began level again after exit, from first level

Which level are you talking about? And what exit?

**Comment by spider2016** [comment] 2015-10-24 09:32
ls -l .supertux2/
итого 12
drwx------ 2 wi wi 4096 окт 24 11:27 addons
-rw------- 1 wi wi 2404 окт 24 11:54 config
drwx------ 2 wi wi 4096 окт 24 11:32 profile1

**Comment by spider2016** [comment] 2015-10-24 09:33
-rw------- 1 wi wi 267 окт 24 11:54 world1.stsg
-rw------- 1 wi wi 338 окт 24 11:38 world2.stsg

**Comment by brmbrmcar** [comment] 2015-10-24 09:34
Are the levels saved?

**Comment by spider2016** [comment] 2015-10-24 09:36
Which level are you talking about? And what exit?
any level
the second
fifth
I go out and my level is first

**Comment by spider2016** [comment] 2015-10-24 09:37
Are the levels saved?
no level will be first

**Comment by brmbrmcar** [comment] 2015-10-24 09:37
Any level.

**Comment by brmbrmcar** [comment] 2015-10-24 09:37
OK.

**Comment by brmbrmcar** [comment] 2015-10-24 09:37
Right...

**Comment by maxteufel** [comment] 2015-10-24 09:46
Now what are you talking about?

> Additional levels not saved too at HDD

Does this mean that add-ons aren't installed to where they belong? Or does it mean that you play a level (what do you consider to be additional then (add-ons/everything but world1/...)) and when you quit the game and open it again your state's been reset?

**Comment by brmbrmcar** [comment] 2015-10-24 09:47
They should be saved in /.supertux2/addons.

**Comment by brmbrmcar** [comment] 2015-10-24 09:47
They changed it.

**Comment by spider2016** [comment] 2015-10-24 09:53
Now what are you talking about?
Additional levels not saved too at HDD:
I mean that saver Additional levels not saved too , for example, forest levels

**Comment by brmbrmcar** [comment] 2015-10-24 09:54
So they aren't saved?

**Comment by maxteufel** [comment] 2015-10-24 09:57
**What** isn't saved? The **state** of the level (the green dot in world1, the star in world2) or a **level you downloaded using the add-on manager** isn't saved to disk?

**Comment by brmbrmcar** [comment] 2015-10-24 09:58
I think they mean the state of the level.

**Comment by maxteufel** [comment] 2015-10-24 10:01
It could be helpful to have a log of stdout (when you run `supertux2` in the command line, pastebin all the output) or even a `strace(1)`, and also the permissions of `~/.supertux2` itself (not shown when you `ls -l` inside it, `ls -la` shows it).

**Comment by spider2016** [comment] 2015-10-24 10:04
Now, directory changed to .supertux2, but levels is now saved.
and errors:

[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/addon/addon_manager.cpp:120 parsing repository.nfo failed: Problem when reading Add-on list: Couldn't open file '/addons/repository.nfo': No such file or directory
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:438 failed to get 'levelsets' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:438 failed to get 'levelsets' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/sector.cpp:598 [levels/misc/menu.stl] Tried spawning Tux in solid matter. Compensating.
[SQUIRREL] [DEBUG] Underground state initialized
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/sector.cpp:598 [levels/misc/menu.stl] Tried spawning Tux in solid matter. Compensating.

**Comment by brmbrmcar** [comment] 2015-10-24 10:06
That's a bug alright.

**Comment by spider2016** [comment] 2015-10-24 10:07
brmbrmcar , is right. state at level

**Comment by brmbrmcar** [comment] 2015-10-24 10:10
Are there any other problems with the build?

**Comment by maxteufel** [comment] 2015-10-24 10:21
> ```
> Couldn't open file '/addons/repository.nfo': No such file or directory
> ```

Why the heck is it looking for the addons directory in `/`? Why would you use `/` as userdir (don't do that, additionally you'd need write permission to `/` (again, **no**))?

> ```
> [WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
> [WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
> [WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
> [WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
> [WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
> [WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:438 failed to get 'levelsets' table entry
>[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:438 failed to get 'levelsets' table entry
> [WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
> ```

This seems more like a broken/unread- or writable savegame file (see <https://github.com/SuperTux/supertux/blob/release/0.3.5/src/supertux/savegame.cpp#L365-L391>, for some reason, it can't load some entries).

Would you post the contents of `profile1/world1.stsg` and `profile1/world2.stsg`

**Comment by spider2016** [comment] 2015-10-24 10:26
i need your email,or  my email is sashachaos@gmail.com

**Comment by maxteufel** [comment] 2015-10-24 10:28
> i need your email,or my email is sashachaos@gmail.com

For what would you need my email? Just post these files to a [pastebin](https://gist.github.com), there shouldn't be any personal information in them.

Alternatively, can you reproduce this with `supertux2 --userdir /tmp/supertux2-userdir-issue199`?

**Comment by spider2016** [comment] 2015-10-24 10:32
I do not make any changes only played 2-3 level. The directory is empty
/home/chaos/.supertux2/addons

**Comment by maxteufel** [comment] 2015-10-24 10:33
You didn't answer any of my questions.

**Comment by spider2016** [comment] 2015-10-24 10:44
http://paste.fedoraproject.org/283189/56834161/

**Comment by spider2016** [comment] 2015-10-24 10:50
http://paste.fedoraproject.org/283193/83770144/

**Comment by spider2016** [comment] 2015-10-24 10:55
I have some archive  and 2 september 2015, addons was not empty.

**Comment by maxteufel** [comment] 2015-10-24 10:56
I get the same error messages using a 0.3.5a build but I can't reproduce the not-saving states. For some reason, in your STSGs, the `("worlds" )` entry is empty. When I use this file it gets automatically reset to a good one.

**Comment by maxteufel** [comment] 2015-10-24 10:57
To avoid the addons error, you'd just go to the Add-on manager and download the addon list, then it will stop complaining.

**Comment by spider2016** [comment] 2015-10-24 12:06
I understand you, but you are no right!!! State is not save!

**Comment by maxteufel** [comment] 2015-10-24 12:10
Can you reproduce that with a **clean** userdir?

**Comment by spider2016** [comment] 2015-10-24 14:06
unfortunately, I deleted directory .supertux2, but state is not save
and:
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:438 failed to get 'levelsets' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:438 failed to get 'levelsets' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/worldmap/worldmap.cpp:674 No level to enter at: 19, 41
[WARNING] /builddir/build/BUILD/supertux-0.3.5a/src/supertux/sector.cpp:598 [levels/misc/menu.stl] Tried spawning Tux in solid matter. Compensating.

**Comment by spider2016** [comment] 2015-10-24 15:45
Now, i compiled official source code and stat is normal. Supertux working good
: [WARNING] /home/chaos/M2/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /home/chaos/M2/supertux-0.3.5a/src/supertux/savegame.cpp:385 failed to get 'worlds' table entry
[WARNING] /home/chaos/M2/supertux-0.3.5a/src/supertux/savegame.cpp:438 failed to get 'levelsets' table entry
[WARNING] /home/chaos/M2/supertux-0.3.5a/src/supertux/savegame.cpp:438 failed to get 'levelsets' table entry

but it works anyway!
Please give me exactly command for compiled gits
git submodule update --init --recursive supertux-master
Error:
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by maxteufel** [comment] 2015-10-24 15:48
> ```
> git submodule update --init --recursive supertux-master
> ```

Git doesn't take a directory as argument. You need to be in that directory to run the command.

**Comment by maxteufel** [comment] 2015-10-24 15:49
> Now, i compiled official source code and stat is normal. Supertux working good

The official 0.3.5a source code? If so, please close this issue. Thanks.

**Closed** 2015-10-24 18:26 UTC
Labels: involves:functionality, status:needs-information, type:bug
