### ISSUE TITLE
Already installed level pack is still on

### ISSUE THREAD

**Issue by matstr-hue** [SuperTux/supertux#1580] opened 2020-11-10 20:23 UTC
Whenever I enter the game and go to check if new levels are available to download this level pack is popping up and it's annoying.
![broken download link](https://user-images.githubusercontent.com/74267729/98729273-f5296a80-239a-11eb-9989-5b367e5c6fe3.png)

**Comment by matstr-hue** [comment] 2020-11-11 09:14
Whoops! I uploaded wrong screenshot. Sorry! Here's a correct one.
![broken download link](https://user-images.githubusercontent.com/74267729/98792322-9a2d5d00-2406-11eb-9840-7a7838fd3be4.png)

**Comment by serano01** [comment] 2020-12-08 10:47
I could not reproduce this. But sometimes I have to delete the addons-folder and refresh the whole thing in-game, otherwise the already downloaded add-ons clash with other/older versions.

**Comment by matstr-hue** [comment] 2020-12-13 12:18
Problem solved! Thanks for help, serano!

**Comment by serano01** [comment] 2020-12-13 15:14
Well then, I'll close this.

**Closed by serano01** 2020-12-13 15:14 UTC
