### ISSUE TITLE
Changing the key setup still allows for default keys to be used

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#592] opened 2016-09-05 17:47 UTC
If you change some of the keys, the old ones will still work. This may be an annoyance to players and could potentially cause bugs.

**Comment by Karkus476** [comment] 2016-09-05 20:35
@brmbrmcar Can you please give an example and some steps to reproduce?

**Comment by brmbrmcar** [comment] 2016-09-05 20:36
Just change any keys, restart the game and use the old keys.

**Comment by Karkus476** [comment] 2016-09-05 20:55
Okay, here's how I did it, using my build of commit 0b3636d5ca:
- Start SuperTux
- Go to options in the main menu
- Go to Keyboard Setup
- Note what your action key is currently
- Change it to right shift or something else
- Click Back, Back, and then Quit
- Start SuperTux again
- Look at your keyboard setup. It should display what it used to be (at step 4) and.
- Now play a level, and both keys should work as your action key
Notes:
 - Does not work in-game.
 - Does not work if you close the window, rather than go back to quit

**Comment by tobbi** [comment] 2016-09-05 21:03
This might not be a bug but intended behaviour: https://github.com/SuperTux/supertux/blob/c8dbabbb04e61e6731041bdce539cd734d326194/src/control/keyboard_manager.cpp#L184

**Comment by Karkus476** [comment] 2016-09-05 21:06
@tobbi I fail to see how two keys performing the same function is intended behaviour.

**Comment by Karkus476** [comment] 2016-09-05 21:18
This seems to be some kind of backup, so that even if you set all the keys randomly, you can still navigate the menu.

**Comment by qwertychouskie** [comment] 2016-09-05 22:45
Seems unnecessary, players can just use the mouse...

**Comment by paezao** [comment] 2016-09-27 00:54
Can you change how you navigate the menu? I think that shouldn't be changeable tbh.

**Comment by paezao** [comment] 2016-09-27 14:43
Yes looks like it is saving my last keys. Ive changed all keys to WASD and JK and I can still use the arrows and space.

**Comment by christ2go** [comment] 2018-03-01 16:45
The issue is [here](https://github.com/SuperTux/supertux/blob/a4bb52b375d22eaa9c17c2fa49e1fca086986f07/src/control/keyboard_config.cpp#L82). The default keys are not deleted from the keymap. Thsi can be fixed by replacing this line with 
`bind_key(static_cast<SDL_Keycode>(key),static_cast<Controller::Control>(i));` 

Or is this expected behaviour? In any case this has to be fixed for multiplayer.

**Comment by maxteufel** [comment] 2018-03-01 16:58
As @tobbi points out in https://github.com/SuperTux/supertux/issues/592#issuecomment-244811120 this seems to be intended behavior *for the menus*. However, I do agree with @Karkus476 (https://github.com/SuperTux/supertux/issues/592#issuecomment-244811402) as well.

Since the former seems to be a good thing, I would suggest using the default keys in the menu and the custom keys while playing in the level (and Editor::active, but not menu, maybe).

Since you can argue for ease of code and consistency though, I'm not entirely sure if that's the right thing to do. Decide to do one thing, document it in appropriate comments, explain the reasons and the alternatives and it should be fine.

**Comment by tobbi** [comment] 2018-12-08 22:55
Is this really prio high? In any case, we won't make it for 0.6.0

**Comment by HybridDog** [comment] 2019-02-21 17:07
This is very annoying to me. I use the alt+f4 and alt+tab window manager key combinations and when I press alt, in supertux something happens. You do not need Action to navigate in the menu to fix a broken key combination.

**Closed** 2019-12-09 00:13 UTC
Labels: priority:high, type:bug
