### ISSUE TITLE
Things to do by 0.4.2

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#213] opened 2015-10-30 13:47 UTC
It has to be done.

**Comment by Karkus476** [comment] 2015-10-30 21:12
We could do with a list of things to be added/fixed before 0.4.2

**Comment by brmbrmcar** [comment] 2015-10-30 21:12
Yes.

**Comment by Karkus476** [comment] 2015-10-30 21:16
I suppose here is a good place to make that list?
1) Further develop the concepts introduced in 'A Ghostly World' and 'Light and Magic' with new levels and even features

**Comment by brmbrmcar** [comment] 2015-10-30 21:21
Yes, it is.

**Comment by maxteufel** [comment] 2015-10-31 07:24
As stated in #71, we're trying to follow <http://semver.org/> starting with the 0.4.0 release. Because this is (in my opinion) not a bugfix, this shouldn't increase the patch version (z in x.y.z) but this would actually be release 0.5.0.

Generally, "Things to do by <version>" can be opened as separate issues and then assigned to Milestone "post-0.4.0".

**Comment by brmbrmcar** [comment] 2015-10-31 08:29
WE need at least 0.4.2 for 0.4.x.

**Comment by maxteufel** [comment] 2015-10-31 08:35
Oh my god, is this so dramatic to not have 0.4.2 (if you want it, take the final 0.4.0 release when it's done and find two bugs)? It's just annoying, for users and packagers to not know what a version increase means when you don't follow a **sane** versioning system.

**Comment by Karkus476** [comment] 2015-10-31 08:57
@maxteufel We don't really have a versioning system, as far as I can see we just make it up as we go along. But you already know that.

**Comment by Karkus476** [comment] 2015-10-31 08:59
I actually think we should jump to 2.0.0 and then use <milestone>.<new features>.<bugfixes>

**Comment by brmbrmcar** [comment] 2015-10-31 09:35
No.

**Comment by maxteufel** [comment] 2015-10-31 13:17
> We don't really have a versioning system, as far as I can see we just make it up as we go along.

@Karkus476: We **didn't have** one, but after the report in #71 we decided to introduce [semver](http://semver.org/) starting from release 0.4.0 (the discussion mainly happened in IRC, not on GitHub), as semver is what most projects use these days.

**Comment by Karkus476** [comment] 2015-10-31 15:45
Oh, I see, thanks for the clarification. I guess that SemVer is the best way to go about versioning a project like this. I didn't realise and agreement had been made.

**Comment by maxteufel** [comment] 2015-10-31 15:50
I'll close this now, please open separate issues for real ideas to improve the forest world.

**Closed by maxteufel** 2015-10-31 15:50 UTC

**Comment by Karkus476** [comment] 2015-10-31 15:52
@maxteufel Good idea

**Comment by maxteufel** [comment] 2015-10-31 15:52
Note that in issues, you can actually make lists (even tickable), like this:

- [x] `- [x] This is some text`
- [ ] `- [ ] This text stays unticked`

**Comment by Karkus476** [comment] 2015-10-31 15:54
Thanks?
- [ ]
- [x]

**Comment by maxteufel** [comment] 2015-10-31 15:55
You'll need to put actual text behind the brackets, it won't work if you don't do that.

If the list's in the original post, GitHub will add "x of y tasks done" to the issues overview.

**Comment by Karkus476** [comment] 2015-10-31 15:56
I will soon be a GitHub ninja!
