### ISSUE TITLE
Pressing Esc in credits opens level pause menu

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1232] opened 2019-11-26 23:56 UTC
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
When I press Esc in credits screen, I return to main menu immediately.

##### Actual behavior
When I press Esc on credits screen, it shows a menu that looks like I'm inside a level, with stuff like “Abort level” and “Restart level”. **This is a regression from 0.6.0**!

##### Steps to reproduce actual behavior
1. Open the credits screen
2. Press Esc

**Comment by Rusty-Box** [comment] 2019-11-26 23:57
@weluvgoatz For you this is. Third time's the charm, isn't it? ;D

**Comment by weluvgoatz** [comment] 2019-11-27 00:02
@Wuzzy Are you playing in English? The fact that the string "Credits" is
translatable might be the cause...

**Comment by Wuzzy2** [comment] 2019-11-27 00:09
I played in German.
As soon I play in English, the bug disappears. That's funny.

**Comment by weluvgoatz** [comment] 2019-11-27 00:12
I can fix this soon. The "Credits" token that the code uses to do this
should be changed to something untranslatable...

**Comment by weluvgoatz** [comment] 2019-11-29 09:06
This has been fixed. Someone close this, please.

**Closed** 2019-11-29 09:15 UTC
