### ISSUE TITLE
MrBomb Bug

### ISSUE THREAD

**Issue by SalomonDFanSuperTux** [SuperTux/supertux#1574] opened 2020-11-09 15:13 UTC
SuperTux version: 0.6.2
This bug it's a little bit strange, one day i was playing SuperTux and i was creating levels and when killed a spiky and mrbomb togeter and the metal corpse of spiky slide in platform xD

This happens with the new recoil of the bomb
![Bug](https://user-images.githubusercontent.com/74196506/98558922-c6b96b80-2284-11eb-91f2-08a1c56ad421.PNG)
PD: The spiky was not there

Hope you can fix this bug in a future update =)

**Comment by LizzyBach** [comment] 2020-11-10 12:26
What do you mean?

**Comment by Ordoviz** [comment] 2020-11-10 13:15
Possible duplicate of #1227

**Comment by SalomonDFanSuperTux** [comment] 2020-11-10 19:36
Yeah

**Comment by Semphriss** [comment] 2022-01-02 08:20
If it is a duplicate of another issue (which is closed! :tada:), I will close this.

**Closed by Semphriss** 2022-01-02 08:20 UTC
