### ISSUE TITLE
Crashing for some levels

### ISSUE THREAD

**Issue by stelariusinfinitek** [SuperTux/supertux#564] opened 2016-08-25 12:18 UTC
**SuperTux version:** 0.4.0-2 
**System information:** *(details about your kernel, operating system, or distribution)* 

OS : Arch Linux
Kernel : 4.7.1
GPU : Nvidia 9400GT
GPU driver : Nouveau

##### Actual behavior 

When I want to play a level, let's say the 5th one, the game crashes. It doesn't happen with all levels but right now I can't advance.

##### Steps to reproduce actual behavior Try to play this level 

![2016-08-25-151516_1280x1024_scrot](https://cloud.githubusercontent.com/assets/18717816/17968677/c5e5657a-6ad6-11e6-93f8-121025bdbeb1.png)

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

Process 2347 (supertux2) of user 1000 dumped core.

```
Stack trace of thread 2347:
#0  0x00000000004edb19 _ZNK4lisp4Lisp8get_lispEPKc (supertux2)
#1  0x000000000054c825 _Z16reader_get_layerRKN4lisp4LispEi (supertux2)
#2  0x000000000057f031 _ZN19CloudParticleSystem5parseERKN4lisp4LispE (supertux2)
#3  0x000000000053c066 _ZN6Sector12parse_objectERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN4lisp4LispE (supertux2)
#4  0x000000000053f72a _ZN6Sector5parseERKN4lisp4LispE (supertux2)
#5  0x0000000000531388 _ZN5Level4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (supertux2)
#6  0x000000000052b7ed _ZN11GameSession13restart_levelEb (supertux2)
#7  0x000000000052c60d _ZN11GameSessionC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEER8SavegameP10Statistics (supertux2)
#8  0x00000000004c5299 _ZN8worldmap8WorldMap6updateEf (supertux2)
#9  0x00000000004abf38 _ZN13ScreenManager16update_gamelogicEf (supertux2)
#10 0x00000000004ad140 _ZN13ScreenManager3runER14DrawingContext (supertux2)
#11 0x00000000004a474a _ZN4Main11launch_gameEv (supertux2)
#12 0x00000000004a5bdc _ZN4Main3runEiPPc (supertux2)
#13 0x00000000004a0a83 main (supertux2)
#14 0x00007f994595a291 __libc_start_main (libc.so.6)
#15 0x00000000004a381a _start (supertux2)

Stack trace of thread 2352:
#0  0x00007f9945a1948d poll (libc.so.6)
#1  0x00007f993905b121 n/a (libpulse.so.0)
#2  0x00007f993904c8f1 pa_mainloop_poll (libpulse.so.0)
#3  0x00007f993904cf8e pa_mainloop_iterate (libpulse.so.0)
#4  0x00007f993904d040 pa_mainloop_run (libpulse.so.0)
#5  0x00007f993905b069 n/a (libpulse.so.0)
#6  0x00007f9938df9ed8 n/a (libpulsecommon-9.0.so)
#7  0x00007f9945520454 start_thread (libpthread.so.0)
#8  0x00007f9945a227df __clone (libc.so.6)

Stack trace of thread 2353:
#0  0x00007f99455260f7 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f993905b708 pa_threaded_mainloop_wait (libpulse.so.0)
#2  0x00007f994718e429 n/a (libopenal.so.1)
#3  0x00007f99471936c7 n/a (libopenal.so.1)
#4  0x00007f9945520454 start_thread (libpthread.so.0)
#5  0x00007f9945a227df __clone (libc.so.6)

Stack trace of thread 2348:
#0  0x00007f99455284f7 do_futex_wait.constprop.1 (libpthread.so.0)
#1  0x00007f99455285a4 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x00007f99478f176e n/a (libSDL2-2.0.so.0)
#3  0x00007f99478f18c5 n/a (libSDL2-2.0.so.0)
#4  0x00007f99478a4c93 n/a (libSDL2-2.0.so.0)
#5  0x00007f99478a482c n/a (libSDL2-2.0.so.0)
#6  0x00007f99478f1439 n/a (libSDL2-2.0.so.0)
#7  0x00007f9945520454 start_thread (libpthread.so.0)
#8  0x00007f9945a227df __clone (libc.so.6)
```

##### Guidelines for reporting issues

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I verified this isn't an issue that's already been reported.
- [x] This report only includes details about **one** (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [x] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by christ2go** [comment] 2016-08-25 12:41
Can reproduce the bug on opensuse Tumbleweed using supertux2 v.0.4.0 with integrated Radeon HD 4350/4550. This bug seems to be resolved in the current git version (and also the release candidates for version 0.5.0), there I can play all Icy-Island levels.

**Comment by maxteufel** [comment] 2016-08-25 13:06
Can we also have the output of gdb's `bt full`? I'd like to understand why this has been happening so it can be avoided in the future.

**Comment by christ2go** [comment] 2016-08-25 13:13
````
0x00000000004fae39 in lisp::Lisp::get_lisp(char const*) const ()
(gdb) bt full
#0  0x00000000004fae39 in lisp::Lisp::get_lisp(char const*) const ()
No symbol table info available.
#1  0x0000000000565415 in reader_get_layer(lisp::Lisp const&, int) ()
No symbol table info available.
#2  0x000000000059ef41 in CloudParticleSystem::parse(lisp::Lisp const&) ()
No symbol table info available.
#3  0x0000000000553246 in Sector::parse_object(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, lisp::Lisp const&) ()
No symbol table info available.
#4  0x000000000055692b in Sector::parse(lisp::Lisp const&) ()
No symbol table info available.
#5  0x0000000000547ede in Level::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
No symbol table info available.
#6  0x000000000054110d in GameSession::restart_level(bool) ()
No symbol table info available.
#7  0x00000000005428d3 in GameSession::GameSession(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Savegame&, Statistics*) ()
No symbol table info available.
#8  0x00000000004cb2fa in worldmap::WorldMap::update(float) ()
No symbol table info available.
#9  0x00000000004adc1d in ScreenManager::run(DrawingContext&) ()
No symbol table info available.
#10 0x00000000004a412b in Main::launch_game() ()
No symbol table info available.
#11 0x00000000004a58e4 in Main::run(int, char**) ()
No symbol table info available.
#12 0x00000000004a0523 in main ()
No symbol table info available.
```
Seems to be an error while loading the level.

**Comment by maxteufel** [comment] 2016-08-25 13:17
Indeed. This has probably been fixed by the s-exp parser changes.

**Closed by maxteufel** 2016-08-25 13:17 UTC
