### ISSUE TITLE
Stacked building blocks jiggle

### ISSUE THREAD

**Issue by zorbakus** [SuperTux/supertux#1031] opened 2019-01-06 00:20 UTC
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
Building blocks don't jiggle.

##### Actual behavior
Stacked building blocks jiggle.

##### Steps to reproduce actual behavior
Put a building block on another one and they start to shake/jiggle. Even the pre-placed ones do. Tux may be stuck in falling animation sometimes when he stands on such block, but nothing game-breaking, you can get off, and most of the time they work fine.

**Comment by tobbi** [comment] 2019-01-06 14:09
Duplicate of #395

**Closed** 2019-01-06 14:10 UTC
