### ISSUE TITLE
Make portable version

### ISSUE THREAD

**Issue by symvizan** [SuperTux/supertux#264] opened 2015-12-14 16:44 UTC
HI!
I would like to see on the downloads page a portable version of SuperTux!
Keep up the good work! :)

**Comment by tobbi** [comment] 2015-12-14 16:47
There's one available on PortableApps.com, though it seems to be outdated (0.3.4). http://portableapps.com/apps/games/supertux-portable

**Comment by tobbi** [comment] 2015-12-14 16:48
We should possibly notify portableapps.com in order for them to release a new version, we could do that once we release 0.4.0

**Comment by Hume2** [comment] 2015-12-14 17:07
Isn't this a dupe of #113 ?

**Comment by tobbi** [comment] 2015-12-14 17:09
I believe @symvizan is referring to a portable windows executable that can be used from a flash drive for example.

**Comment by Hume2** [comment] 2015-12-14 17:22
You can already start SuperTux from a flash disk.

**Comment by tobbi** [comment] 2015-12-14 17:24
Yes, but the settings will be written to the profile folder which isn't on the flash drive.

**Comment by Hume2** [comment] 2015-12-14 17:26
In fact, you can launch SuperTux with modified userdir, but I agree that it's teddious to type it on each SuperTux start.

**Comment by Karkus476** [comment] 2015-12-19 22:06
@symvizan We are going to ask portable games to update their version. If that doesn't work, I'll reopen this.

**Closed by Karkus476** 2015-12-19 22:06 UTC
Labels: category:meta, involves:functionality

**Comment by tobbi** [comment] 2015-12-19 22:07
xref #243 includes that as a TODO item.
