### ISSUE TITLE
Menu text could use some cleanup

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#236] opened 2015-11-22 11:34 UTC
The game's menu currently features text such as this:

* Restart level
* Abort Level
* Quit World

"Level" is once in upper case, once in lowercase.  "Quit" and "Abort" also don't sound all that great, other terminology might be more appropriate such as "Leave World" or "Leave Level".

**Comment by Karkus476** [comment] 2015-11-22 11:42
A problem is that changing this may cause all the translations to need reassigning

**Comment by brmbrmcar** [comment] 2015-11-22 11:44
But you could probably get away with only changing the English, because it will be different in other languages.

**Comment by Karkus476** [comment] 2015-11-22 11:45
Do we have an English translation?

**Comment by brmbrmcar** [comment] 2015-11-22 11:46
English translation for English?

**Comment by Grumbel** [comment] 2015-11-22 11:56
Other idea: World -> Island

**Comment by brmbrmcar** [comment] 2015-11-22 11:58
Leave island? Hmm....

**Comment by brmbrmcar** [comment] 2015-11-22 11:58
Guess it could work.

**Comment by Hume2** [comment] 2016-03-22 07:41
What about:

- Restart Level
- Abort Level
- Leave World

**Comment by MCMic** [comment] 2016-06-14 06:27
Why the uppercase on the first letter for the words other than the first of each option?
This is always weird to me when translating I don’t know If I’m supposed to reproduce this weirdness in French or if I should have an upper case only on the first letter of each sentence as usual.

**Comment by maxteufel** [comment] 2016-06-14 13:14
This is by no means a weirdness but could be seen as title case (<https://en.wikipedia.org/wiki/Letter_case#Headings_and_publication_titles>) which is pretty common in English.

When translating never keep any style elements from the source language unless it is actually necessary. Instead, use a language style appropriate to what you're translating to and keep that consistent across all strings.

**Closed** 2016-06-15 16:01 UTC
Labels: category:code, involves:l10n
