### ISSUE TITLE
No way to change level length/height in the editor?

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#497] opened 2016-07-20 09:21 UTC
There doesn't seem to be any way to change a level's length/height in the editor. Sure, you can change the length/height of each individual tilemap but things like gradients rely on the actual dimensions of the level rather than the dimensions of the tilemaps it contains.

**Comment by maxteufel** [comment] 2016-07-20 09:22
Duplicate of #484, where this is being worked on.

**Comment by tobbi** [comment] 2016-07-20 09:22
An option to resize the whole sector is in #484.

A whole level consists of different sectors, but I still think resizing one sector only should be enough.

**Comment by 165your4** [comment] 2016-07-20 09:23
Oops! Sorry.

**Comment by maxteufel** [comment] 2016-07-20 09:24
Resizing all sectors at once would break things anyway, most likely (depends on the configuration of the sectors, but you know).

**Comment by Hume2** [comment] 2016-07-22 09:39
The thing you can actually do is reviewing #484 .

**Comment by tobbi** [comment] 2016-07-25 01:36
Since this is now merged with master, I'm gonna close it.

**Closed by tobbi** 2016-07-25 01:36 UTC
Labels: category:code, duplicate, involves:editor, type:feature
