### ISSUE TITLE
[Crash]: when the "exploding enemies" explode at "Entrance To The Cave", they give a bsod.

### ISSUE THREAD

**Issue by peginthepenguin** [SuperTux/supertux#3141] opened 2024-12-13 22:05 UTC
### SuperTux Version

v0.6.3-1512-g4e5457f6d

### System Information

Windows 11 64-bit

### Steps To Reproduce Crash

How to recreate my issue.
step 1. play supertux
step 2. enter "entrance to the cave"
step 3. stomp on a emploding enemy.
step 4. wait until the enemy **explodes**.
congratulations, you have crashed the pc!!! Hurray! 

### Additional Information

here are my computers specs:
cpu: 11th gen intel core i5-1135G7  2.4ghz
gpu: integrated graphics

### Guidelines For Reporting Issues

- [X] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [X] I have verified this isn't an issue that's already been reported.
- [X] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue about unintended behavior or a feature request, but rather an actual crash ─ that is, the game closed unexpectedly.
- [X] I have verified this issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [X] In this report, I have only included details about **one** (1) crash.
- [X] If I make a mistake while submitting this report, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by swagtoy** [comment] 2024-12-13 22:58
Working as intended. When the enemies explode, it's fair that your machine should explode too.

Jokes aside, does this happen every time? Are you using the OpenGL 3.3 backend? Does it still occur on other video backends i.e. SDL2 (more importantly, does it also occur with OpenGL2?)

Some more information can help me debug it.

**Comment by peginthepenguin** [comment] 2024-12-14 09:49
im using some kind of OpenGL, version 33 or maybe 3.3. i dont know.

**Comment by MatusGuy** [comment] 2024-12-14 14:58
> crashed the pc

The PC? Like, a blue screen?

If so, this can happen depending on your video driver, so you have two options:
- Update your graphics drivers
- Use the SDL2 backend by going into the game's settings > Video > Change Video System

**Comment by peginthepenguin** [comment] 2024-12-14 15:08
yes, a blue screen, not a green screen, also i have **no way** to update the drivers.
i also changed to sdl2.
and the issue fixed itself???

**Comment by MatusGuy** [comment] 2024-12-14 15:10
SDL2 tends to be more stable than opengl in this game. Can I close this issue?

**Comment by peginthepenguin** [comment] 2024-12-14 15:11
yea

**Closed** 2024-12-14 15:13 UTC
Labels: type:crash
