### ISSUE TITLE
Changing camera mode from autoscroll to normal causes crash in level editor

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#2883] opened 2024-04-02 03:53 UTC
Current nightly.  Title explains it.  I was making a level and I tried changing the camera mode from autoscroll to normal, and it caused the game to crash.  Upon opening the game again, the level name had just disappeared, so I opened the file for the level and the contents of the file were just completely wiped.  This is extremely frustrating.  I hope it gets fixed soon.

**Comment by mrkubax10** [comment] 2024-04-02 09:00
Well since game crashes level is not saved, that's why it's wiped.

**Comment by tobbi** [comment] 2024-04-02 11:14
Proper steps to reproduce:
Change mode to autoscroll, then back to manual **AND THEN hover with your mouse over the camera icon after that**.

Stacktrace:
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  * frame #0: 0x00000001005023cc supertux2`std::__1::vector<Path::Node, std::__1::allocator<Path::Node> >::empty(this=0x0000000000000008 size=0) const at vector:662:23
    frame #1: 0x0000000100502c6e supertux2`Path::is_valid(this=0x0000000000000000) const at path.cpp:242:19
    frame #2: 0x00000001004141be supertux2`Camera::get_settings(this=0x0000000113f95db0) at camera.cpp:170:35
    frame #3: 0x000000010030fcdf supertux2`Tip::set_info_for_object(this=0x000000011de5ab40, object=0x0000000113f95db0) at tip.cpp:56:20
    frame #4: 0x000000010024a0e9 supertux2`EditorLayersWidget::update_tip(this=0x000000011de5a9c0) at layers_widget.cpp:415:17
    frame #5: 0x0000000100249fac supertux2`EditorLayersWidget::on_mouse_motion(this=0x000000011de5a9c0, motion=0x00007ffeefbfec20) at layers_widget.cpp:252:9
    frame #6: 0x0000000100320c78 supertux2`Widget::event(this=0x000000011de5a9c0, ev=0x00007ffeefbfec20) at widget.cpp:31:14
    frame #7: 0x00000001002279a6 supertux2`Editor::event(this=0x000000011db8bd90, ev=0x00007ffeefbfec20) at editor.cpp:879:19
    frame #8: 0x0000000100a70594 supertux2`ScreenManager::process_events(this=0x00000001050454a0) at screen_manager.cpp:408:26
    frame #9: 0x0000000100a71489 supertux2`ScreenManager::loop_iter(this=0x00000001050454a0) at screen_manager.cpp:633:5
    frame #10: 0x0000000100a719cc supertux2`ScreenManager::run(this=0x00000001050454a0) at screen_manager.cpp:674:5
    frame #11: 0x00000001008bcac8 supertux2`Main::launch_game(this=0x000000010521e220, args=0x00007ffeefbff438) at main.cpp:653:21
    frame #12: 0x00000001008be7b6 supertux2`Main::run(this=0x000000010521e220, argc=1, argv=0x00007ffeefbff5e0) at main.cpp:739:9
    frame #13: 0x000000010000683d supertux2`main(argc=1, argv=0x00007ffeefbff5e0) at main.cpp:30:21
    frame #14: 0x00007fff721eecc9 libdyld.dylib`start + 1
(lldb) 
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  * frame #0: 0x00000001005023cc supertux2`std::__1::vector<Path::Node, std::__1::allocator<Path::Node> >::empty(this=0x0000000000000008 size=0) const at vector:662:23
    frame #1: 0x0000000100502c6e supertux2`Path::is_valid(this=0x0000000000000000) const at path.cpp:242:19
    frame #2: 0x00000001004141be supertux2`Camera::get_settings(this=0x0000000113f95db0) at camera.cpp:170:35
    frame #3: 0x000000010030fcdf supertux2`Tip::set_info_for_object(this=0x000000011de5ab40, object=0x0000000113f95db0) at tip.cpp:56:20
    frame #4: 0x000000010024a0e9 supertux2`EditorLayersWidget::update_tip(this=0x000000011de5a9c0) at layers_widget.cpp:415:17
    frame #5: 0x0000000100249fac supertux2`EditorLayersWidget::on_mouse_motion(this=0x000000011de5a9c0, motion=0x00007ffeefbfec20) at layers_widget.cpp:252:9
    frame #6: 0x0000000100320c78 supertux2`Widget::event(this=0x000000011de5a9c0, ev=0x00007ffeefbfec20) at widget.cpp:31:14
    frame #7: 0x00000001002279a6 supertux2`Editor::event(this=0x000000011db8bd90, ev=0x00007ffeefbfec20) at editor.cpp:879:19
    frame #8: 0x0000000100a70594 supertux2`ScreenManager::process_events(this=0x00000001050454a0) at screen_manager.cpp:408:26
    frame #9: 0x0000000100a71489 supertux2`ScreenManager::loop_iter(this=0x00000001050454a0) at screen_manager.cpp:633:5
    frame #10: 0x0000000100a719cc supertux2`ScreenManager::run(this=0x00000001050454a0) at screen_manager.cpp:674:5
    frame #11: 0x00000001008bcac8 supertux2`Main::launch_game(this=0x000000010521e220, args=0x00007ffeefbff438) at main.cpp:653:21
    frame #12: 0x00000001008be7b6 supertux2`Main::run(this=0x000000010521e220, argc=1, argv=0x00007ffeefbff5e0) at main.cpp:739:9
    frame #13: 0x000000010000683d supertux2`main(argc=1, argv=0x00007ffeefbff5e0) at main.cpp:30:21
    frame #14: 0x00007fff721eecc9 libdyld.dylib`start + 1

**Comment by tobbi** [comment] 2024-04-02 11:33
I wouldn't call this urgent, but there you go, it's fixed now.

**Closed** 2024-04-02 11:33 UTC
Labels: type:bug, priority:urgent, involves:editor, category:code, type:crash
