### ISSUE TITLE
Crash while holding Mr. IceBlock in edit mode

### ISSUE THREAD

**Issue by mark-otaris** [SuperTux/supertux#307] opened 2015-12-29 05:09 UTC
I am using supertux2 0.3.5a, version packaged in Fedora 23, Linux 4.2.8-300.fc23.x86_64, no core dump generated. SuperTux crashed while I was in the level “On The Road Again” in Bonus Island II.

Steps to reproduce (seems to work in any level):

1. Open the console and enable edit mode with `edit()`.
2. Squish one of the Mr. IceBlock badguys in the level.
3. Carry it by running into it while pressing the action button.
4. Jump into one of the holes and fall to the bottom of the screen.

At this point, the game should crash. This does not seem to be due to switching to ghost mode while carrying Mr. IceBlock, since opening the console and executing `ghost()` while carrying Mr. IceBlock does not make the game crash. Furthermore, dying in another way than by falling to the bottom of the screen while in edit mode and carrying Mr. IceBlock does not make the game crash.

**Comment by mark-otaris** [comment] 2015-12-29 09:22
I reproduced the issue in version 0.4.0, following the same steps as above with the difference that the command to run is `Level_edit()` instead of `edit()`.

**Comment by maxteufel** [comment] 2015-12-29 09:28
I was able to reproduce this with `edit()` in 0.4.0, with Mr. Bomb. I can provide a core dump, I guess.

**Comment by maxteufel** [comment] 2015-12-29 09:36
GDB `bt full`: http://sprunge.us/CDRJ

**Comment by norpol** [comment] 2015-12-29 15:37
Thanks for fixing.
Slightly off-topic: See other [hacks](https://github.com/SuperTux/supertux/search?utf8=%E2%9C%93&q=hack).

**Comment by maxteufel** [comment] 2015-12-30 09:28
This needs more validation, I don't really know if this is fixed (well, one part might be, as it failed at an `assert()` statement before, which is now handled in the code). What seems to happen with `--debug` enabled is that due to pressing Action, it tries to release you from ghost mode, catches you again, releases, ...

**Comment by Hume2** [comment] 2016-01-04 06:48
When I grab an object and I try to go to the ghost mode, the mode immediatelly changes back. Is that intended?

**Comment by mark-otaris** [comment] 2016-01-04 19:57
On Sun, 2016-01-03 at 22:48 -0800, Hume2 wrote:
> When I grab an object and I try to go to the ghost mode, the mode
> immediatelly changes back. Is that intended?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/SuperTux/supertux/issues/307#issuecomment-16859659
> 5

Yes, the action key is also used to get out of ghost mode.

**Comment by Hume2** [comment] 2016-01-08 20:22
So it's intended. May I close it then?

**Comment by Karkus476** [comment] 2016-01-08 23:03
No. The ice cube should be dropped, and it should wait for a new press of the action key to go back

- Karkus

**Comment by maxteufel** [comment] 2016-06-29 08:19
@mark-otaris Can you please test the change in #437?

**Closed** 2016-07-02 15:31 UTC
Labels: category:code, involves:functionality, priority:medium, status:needs-information, type:bug
