### ISSUE TITLE
Buttjumping on trampoline 'bonus block' into impossible position

### ISSUE THREAD

**Issue by plonibarploni** [SuperTux/supertux#990] opened 2018-12-19 05:44 UTC
Supertux 0.6.0-rc.1 (possibly also in older versions)
In 'Above the Arctic Skies', if you buttjump the bonus block that reveals the trampoline right next to the wall, Tux is moved into the wall, and you have to jump to get out of the wall (else you take a hit).

![screenshot at 2018-12-19 00-00-43](https://user-images.githubusercontent.com/44826203/50201040-89f9c980-0326-11e9-9a85-1aacb5795580.png)

I would expect that Tux would land on top of the trampoline and start bouncing away.

**Comment by plonibarploni** [comment] 2018-12-20 01:59
Similar issue also appears in 'Bouncy Coils':
![bouncycoils](https://user-images.githubusercontent.com/44826203/50259118-bbc76a80-03d0-11e9-9fef-4d6da0ab30f3.gif)

**Comment by brmbrmcar** [comment] 2018-12-20 19:09
Certainly looks like something new with the engine. This doesn't happen in my older version when buttjumping a trampoline block.

**Comment by HybridDog** [comment] 2019-10-07 09:39
![2019-10-07-113051_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/66300902-696f2000-e8f6-11e9-958a-3d6a7727daa4.jpg)

Maybe it is possible to disallow the collision calculation to move Tux or other objects into tiles;
it could fix this issue, #1048, #535, #1075, and more.

**Comment by Zwatotem** [comment] 2019-10-07 13:38
> Maybe it is possible to disallow the collision calculation to move Tux or other objects into tiles;
> it could fix this issue, #1048, #535, #1075, and more.

_And by the way kill a lot of speedrunning shortcuts. :( _ 

That's a sensible solution, although player would still get hurt by the appearing trampoline, which is still not fair to the player.

**Comment by HybridDog** [comment] 2019-10-07 18:25
> And by the way kill a lot of speedrunning shortcuts. :(

It would also break one of my levels where you have to move through the floor.

> […] which is still not fair to the player, so some additional code is needed.

The spawning trampoline could probably get a small collision box which moves the player up. Currently, while the trampoline goes up, it has no collision box (as can be inferred from the screenshot).

**Comment by Wuzzy2** [comment] 2019-11-27 00:03
Reproduced in 0.6.1 beta 1.

With an important difference: This maneuver is now deadly. It insta-kills Tux, no matter if small, big, fire, etc.

**Comment by Rusty-Box** [comment] 2019-11-27 00:10
We might really need a way coding wise that prevents death by trampoline from bonus blocks. Pure level design adjustments possibly won't fix everything.

**Closed** 2019-11-28 15:38 UTC
Labels: category:code, category:levels, priority:urgent, status:in-progress, type:level

**Comment by plonibarploni** [comment] 2020-01-08 22:42
This issue is not (yet) fixed - see https://github.com/SuperTux/supertux/pull/1246#issuecomment-572292947.

**Comment by Zwatotem** [comment] 2020-01-09 07:17
I wasn't able to reproduce it. Does it occur on 0.6.1 or on latest master builds?

**Comment by plonibarploni** [comment] 2020-01-09 16:29
This occurs on the latest master builds. On the latest release (0.6.1.1) it works as expected.

**Comment by Zwatotem** [comment] 2020-01-10 11:08
I found the cause and repaired. I'll push it as soon as I get confirmation, that it doesn't break anything else.
