### ISSUE TITLE
Dead badguys are being pushed by explosions

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1227] opened 2019-11-26 23:48 UTC
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
Dead badguys are not being pushed by explosions.

##### Actual behavior
Dead badguys are being pushed by explosions, which looks hilariously glitchy.

##### Steps to reproduce actual behavior
1. Kill any walking enemy (snowball, spiky, walking leaves)
2. Cause a explosion (e.g. bomb) very quickly afterwards, directly after the badguy died

**Comment by Rusty-Box** [comment] 2019-11-27 00:01
This should definitely get fixed.
@weluvgoatz Since you made it you might know how to fix this.

**Comment by weluvgoatz** [comment] 2019-11-27 00:33
Well, I really only have extended a previously implemented behaviour to normal bombs, so whoever originally added shortfuses shall know what the issue is ;)

**Comment by HybridDog** [comment] 2020-05-09 16:07
I cannot reproduce this; the bomb code tests for is_active() and the dead snowball is not pushed.
![fot_2020-05-09-18:05:56_678792496](https://user-images.githubusercontent.com/3192173/81478806-e1e8e700-921f-11ea-9afe-eac5d4fe71d9.jpg)

**Comment by Wuzzy2** [comment] 2020-05-09 16:16
This bug is old, maybe it got fixed “by accident”? ;-)

I did not re-test this, however.

FYI: If I remember correctly, I was able to reliably trigger this bug back in the days.

**Comment by Zwatotem** [comment] 2020-08-18 20:51
I took a look, and it's fixed. Closing

**Closed by Zwatotem** 2020-08-18 20:51 UTC
Labels: category:code, priority:high, type:bug
