### ISSUE TITLE
Segfault while running latest build of Supertux

### ISSUE THREAD

**Issue by mikeweilgart** [SuperTux/supertux#1385] opened 2020-04-25 03:17 UTC
**SuperTux version:** today's build from master.  No version number, so here's md5sum output: `a18c81beb14ef1c228f4074e785411b6  SuperTux_2-.glibc2.27-x86_64.AppImage`
**System information:** Kubuntu 20.04

##### Expected behavior
Program should not segfault ever.  :)

##### Actual behavior
Program crashed; `/var/log/syslog` reveals it was a segfault.

##### Steps to reproduce actual behavior
Not sure about reproducing it.  This was just my son playing a level, he wasn't doing anything special at the time.  (Just walking around.  I was watching.)  Then the program crashed.  I'm hoping the log lines in syslog will be useful.

##### Additional debugging information

```
Apr 24 20:02:44 weilgart-thinkpad-l540 kernel: [203305.392620] supertux2[80659]: segfault at 10 ip 0000558b46a31ace sp 00007ffc1c7fc5f0 error 4 in supertux2[558b46753000+4fe000]
Apr 24 20:02:44 weilgart-thinkpad-l540 kernel: [203305.392629] Code: 10 4c 24 0c f3 0f 10 15 74 9c 16 00 f3 0f 58 ca 0f 2f c8 0f 83 11 ff ff ff 48 8b bb b0 01 00 00 48 8d 15 85 80 f2 ff 48 8b 07 <48> 8b 40 10 48 39 d0 75 19 48 89 5f 08 e9 1f ff ff ff 8b 93 24 01
Apr 24 20:02:45 weilgart-thinkpad-l540 systemd[1519]: tmp-.mount_SuperTa6Ydze.mount: Succeeded.
Apr 24 20:02:45 weilgart-thinkpad-l540 systemd[1]: tmp-.mount_SuperTa6Ydze.mount: Succeeded.
Apr 24 20:02:45 weilgart-thinkpad-l540 systemd[49522]: tmp-.mount_SuperTa6Ydze.mount: Succeeded.
Apr 24 20:02:45 weilgart-thinkpad-l540 systemd[5051]: tmp-.mount_SuperTa6Ydze.mount: Succeeded.
Apr 24 20:03:51 weilgart-thinkpad-l540 dbus-daemon[947]: [system] Activating service name='com.ubuntu.WhoopsiePreferences' requested by ':1.1377' (uid=1002 pid=82089 comm="/usr/bin/kcmshell5 kcm_whoopsie " label="unconfined") (using servicehelper)
Apr 24 20:03:51 weilgart-thinkpad-l540 dbus-daemon[947]: [system] Successfully activated service 'com.ubuntu.WhoopsiePreferences'
Apr 24 20:03:51 weilgart-thinkpad-l540 com.ubuntu.WhoopsiePreferences[82097]: Acquired the name: com.ubuntu.WhoopsiePreferences
```

I'm not sure if the "Whoopsie" lines are related, but they seem to be.  Also I'm not sure if they indicate the existence of further usable debugging info, but if so I would be happy to follow any instructions on how to provide that.

**Comment by tobbi** [comment] 2020-04-25 09:14
I wasn't able to reproduce the issue in a Kubuntu VM. Could you try building SuperTux yourself and see if the issue persists? Also, you'd then get debug symbols with the build that should give us more info (line numbers etc).

**Comment by Narre** [comment] 2020-04-25 12:34
I've got an old computer in the attic (year ~2000), where SuperTux crashes quite often. I just tried running it for laughs and I assumed it kept crashing because it kept running out of memory, so I never investigated it, but I could use that computer to make SuperTux crash and see what it has to tell.

Also, SuperTux crashes on my main computer, too, but definitely for a different reason. On the old one, it just "closes" at any point, whereas on my main computer, it only happens if it manages to reach 0 FPS for at least 3-4 seconds. My frames don't usually drop, but there are levels that manage to lag SuperTux quite a bit, especially 'Tower of Ghosts', which I cannot run at anything greater than 5-10 FPS.

**Comment by Narre** [comment] 2020-04-25 15:57
Also, some (a.k.a. almost ALL) contrib levels made for older versions of SuperTux are completely broken in 0.6, sometimes they are just missing some assets, sometimes some scripts don't work, but sometimes it can completely crash the game. An example of this would be level 'Hedgehog launch' from Hume's islands - as soon as you jump into the pipe, the game just crashes. This is most likely the reported problem. Terminal output: (note: the directory is called supertux061 but it is a clone of the repository, freshly updated)

**STARTING HUME'S ISLANDS**

[WARNING] /home/narre/supertux061/src/worldmap/worldmap_parser.cpp:141 Unknown token 'camera' in worldmap

**STARTING HEDGEHOG LAUNCH**

[WARNING] /home/narre/supertux061/src/video/texture_manager.cpp:336 Couldn't load texture '/images/background/arctis.jpg' (now using dummy texture): Couldn't open '/images/background/arctis.jpg': 11
[WARNING] /home/narre/supertux061/src/video/texture_manager.cpp:336 Couldn't load texture '/images/background/arctis_top.jpg' (now using dummy texture): Couldn't open '/images/background/arctis_top.jpg': 11
[WARNING] /home/narre/supertux061/src/video/texture_manager.cpp:336 Couldn't load texture '/images/background/arctis_bottom.jpg' (now using dummy texture): Couldn't open '/images/background/arctis_bottom.jpg': 11

**ENTERING THE PIPE**

Segmentation fault (core dumped)

**Comment by Narre** [comment] 2020-04-25 15:58
I've noticed this in more levels, but this is the one I remember clearly. It's definitely not a problem unique to this level though.

**Comment by tobbi** [comment] 2020-04-26 15:07
Can we please keep this issue on-topic? File a new issue for the other stuff.

**Comment by Narre** [comment] 2020-04-26 20:14
How is this off-topic? I'm suggesting how the game might have crashed and the second possibility I found literally causes a segfault - therefore it very likely may be the exact problem reported, it's not like SuperTux segfaults at every other opportunity.

**Comment by mikeweilgart** [comment] 2020-04-28 05:08
> I wasn't able to reproduce the issue in a Kubuntu VM. Could you try building SuperTux yourself and see if the issue persists? Also, you'd then get debug symbols with the build that should give us more info (line numbers etc).

Just to clarify, this doesn't happen all the time, only sometimes.  So building SuperTux myself won't tell me if the issue *persists,* since it's not really deterministic now.  However, I can build it myself and then use the resulting binary for a while if a crash on that binary would then give you more information.  (?)

Here are the log lines (from `/var/log/syslog` from the latest crash (using the same version as the first crash; I didn't build this):

```
Apr 27 21:56:45 weilgart-thinkpad-l540 kernel: [  363.703599] supertux2[2129]: segfault at 18 ip 00007f1cd901efb8 sp 00007ffd272fe2c0 error 6 in i965_dri.so[7f1cd8fba000+8b0000]
Apr 27 21:56:45 weilgart-thinkpad-l540 kernel: [  363.703614] Code: c5 49 8d 04 83 49 8d 6b 08 48 89 83 58 23 01 00 43 8d 04 a2 45 89 d4 89 44 24 08 8b 44 24 0c 44 29 d0 89 44 24 0c 0f 1f 40 
00 <44> 89 65 fc 8b 44 24 0c 48 89 ea 45 31 c9 c7 45 f8 01 00 80 14 4c
```

Can you please tell me how to get the additional info you need?  I can start up SuperTux in a special way each time I start it, or give output from a particular command, or whatever you need.  If I build it from source, is there some particular compiler flag I should use that will include line numbers and debug info and so forth that you need?

(For purposes of gauging the instructions you give: I don't work in C or C++, although I can read C decently well.  However I have a Linux sysadmin background, programming experience in Python et. al., can read man pages, and I've used `gcc` a couple times on code I didn't write myself.)

**Comment by tobbi** [comment] 2020-04-30 19:39
Does starting SuperTux with --renderer sdl fix things?

**Comment by HybridDog** [comment] 2020-05-04 17:51
SuperTux crashed for me when I played the Tower of Ghosts level.
Here's a backtrace: https://pastebin.com/raw/1r7rw2mj
I used supertux2 v0.6.2-beta.1-3-gbcb66d6f9.

**Comment by tobbi** [comment] 2020-05-04 17:54
```cpp
m_sync = glFenceSync(GL_SYNC_GPU_COMMANDS_COMPLETE, GL_NONE_BIT);
```

This seems to be a common source of crashes. If I knew more about OpenGL, I'd find a way to rewrite that code, but alas I don't.

**Comment by HybridDog** [comment] 2020-05-04 17:58
https://github.com/SuperTux/supertux/blob/bcb66d6f920f03b44d590b190e13ddfb46da6e79/src/video/gl/gl_pixel_request.cpp#L48-L60

**Comment by tobbi** [comment] 2020-05-06 12:23
@HybridDog Since it's crashing inside i965_dri.so (which is inside the driver) is there anything we can do at all? Considering it works on other systems, I'd assume that our calling of the gl functions is proper.

**Comment by tobbi** [comment] 2020-05-06 12:29
What I mean is: Is this our bug or not?

**Comment by HybridDog** [comment] 2020-05-06 14:00
I still use the same driver and opengl than before, when it didn't crash, so I think the bug is in SuperTux.
Maybe the x or y value is out of bounds.

**Comment by tobbi** [comment] 2020-05-06 15:18
Try building supertux yourself and getting a regression range using `git bisect`. That way we can find out what triggered it.

**Comment by HybridDog** [comment] 2020-05-06 16:00
For the bisect we first need a way to reproduce the crash.

Btw: ccache can help to make re-building significantly faster; if I remember correctly, to make it work you need to install ccache and add `export PATH=/usr/lib/ccache:$PATH` to the bashrc.

**Comment by HybridDog** [comment] 2020-05-06 16:52
I've found a way to cause a crash, but I don't know if it's reliable:
Enter this level and wait for some seconds.  [level7.stl.zip](https://github.com/SuperTux/supertux/files/4588184/level7.stl.zip)

**Comment by tobbi** [comment] 2020-05-08 13:08
I'm gonna close this bug as a valid workaround has been found.

**Closed by tobbi** 2020-05-08 13:08 UTC
