### ISSUE TITLE
supertux windows 64bit sound effect

### ISSUE THREAD

**Issue by amie1972** [SuperTux/supertux#632] opened 2016-10-08 00:20 UTC
**SuperTux version:0.5.0
**System information:windows 10 pro 64bit *(details about your kernel, operating system, or distribution)*

in option menu,sound configurations are disabled.

**Comment by tobbi** [comment] 2016-10-08 00:23
Please re-download the installer from https://github.com/SuperTux/supertux/releases/tag/v0.5.0 and re-run it. See if this fixes the problem

Where did you download the installer from in the first place?

**Comment by tobbi** [comment] 2016-10-08 00:25
This is a duplicate of #613, anyway.

**Closed** 2016-10-08 00:54 UTC
Labels: duplicate

**Comment by amie1972** [comment] 2016-10-08 00:56
By the way in issue #613,this is corrected.
