### ISSUE TITLE
Tux should wear the Christmas hat even in the start screen

### ISSUE THREAD

**Issue by ryonakano** [SuperTux/supertux#747] opened 2017-12-07 08:16 UTC
**SuperTux version:** 0.5.1 in Christmas Mode
**System information:** Linux Kernel 4.10.0, KDE neon 5.11.4, 64bit

##### Actual behavior
![screenshot_20171207_164237](https://user-images.githubusercontent.com/26003928/33704302-511d2948-db6f-11e7-970c-4692fbf83f6e.png)
In Christmas Mode, Tux does not wear Christmas hat in the start screen of levels, instead he wears something strange.

#### Expected behavior
He should wear the Christmas hat even in the start screen.

##### Steps to reproduce actual behavior
Before beginning, ensure your SuperTux is in "Christmas Mode."
![screenshot_20171207_164300](https://user-images.githubusercontent.com/26003928/33704561-580891a6-db70-11e7-9913-e178db8359bc.png)
First, make Tux eaten the fire-flower and worn the Christmas hat like this above.
Then return to worldmap, select any level, and see the start screen.

**Comment by tobbi** [comment] 2017-12-07 15:01
I can't reproduce this. It might be that this issue is fixed with the last development build but wasn't yet backported in 0.5.1. Can you download the latest nightly build from https://download.supertux.org/ and check whether it's fixed there?

**Comment by ryonakano** [comment] 2017-12-07 22:09
![screenshot_20171208_070155](https://user-images.githubusercontent.com/26003928/33741004-190a0edc-dbe6-11e7-9bce-dd0a2cc21f33.png)

I downloaded SuperTux_2-v0.5.0-325-gf6fa35439.glibc-x86_64.AppImage from the link above and conformed that this issue dosen't occur.
I'm sorry for posting a wrong issue. I'll check the link above occasionally and download the latest nightly build.

**Comment by tobbi** [comment] 2017-12-07 22:10
Don't worry about it, we could've backported that fix for 0.5.1, apparently, we forgot about it or didn't deem it a priority. Closing.

**Closed by tobbi** 2017-12-07 22:10 UTC
