### ISSUE TITLE
Expose enemies to scripting

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1320] opened 2020-01-21 02:20 UTC
Enemies in SuperTux should be scriptable.  They already support namespaces, so they could use that.  Scripting for enemies would also be super fun and useful.  

Here's a list of scripts I want for enemies:

kill(type) - This would kill the enemy, either by killfalling it or by burning it.

set_sprite() - This would change the enemy's sprite to a new sprite.

set_action() - This would change the enemy's sprite action.

Please consider, thanks!

**Comment by tobbi** [comment] 2020-01-24 00:20
Duplicate of #366

**Closed** 2020-02-02 23:10 UTC
Labels: category:code, help wanted, involves:scripting, status:needs-discussion, type:idea
