### ISSUE TITLE
Wrong tile colours

### ISSUE THREAD

**Issue by Hume2** [SuperTux/supertux#146] opened 2015-09-20 12:03 UTC
Exit poles display white-and-yellow instead of black-and-white, except the top tiles.
Hanging vines display with a black background.

However, when I open these tiles in graphical editor, they display normally.

It began when Tobbi compressed the images.

**Comment by tobbi** [comment] 2015-09-20 12:05
@165your4: This was your problem as well, wasn't it?

**Comment by NNemesis** [comment] 2015-09-20 15:36
Looking at the PNG files for the affected tiles, it seems that they all have something in common: a tRNS chunk which specifies a specific colour as transparency (in most cases, fully black).

Looking at the goal tiles in particular, the glitched ones have just greyscale information, with a transparency colour set as 0 (fully black), where the tops of the goal have greyscale+alpha information for each pixel.

This doesn't really show that it's the cause of the issue, just an observation.

**Comment by NNemesis** [comment] 2015-09-20 16:34
While looking at this more, I managed to give one of the images for the goal a proper alpha channel, and the bug was still there. Even after replacing that image with one from before Tobbi compressed the images, the bug was still there.

This means that the bug is most likely not caused by the image files but something else.

**Comment by NNemesis** [comment] 2015-09-20 19:38
Okay so after more experimentation I found that, for some reason, I couldn't get SuperTux to use my modified images. Whenever I changed the image for a tile, it would still use the old one.

However, I did once manage to get the hanging vines image replaced with one which I edited, and that fixed the black background issue, which means the problem might still be to do with the transparency.

If any of the more experienced devs know why the new images aren't being used, please let me know so I can find out more about this.

**Comment by Hume2** [comment] 2015-09-21 05:03
Try to delete the images. Maybe you have something like tiles.strf bug too.

**Comment by tobbi** [comment] 2015-09-21 15:54
Screenshot: http://imgur.com/P1iHzxc

**Comment by NNemesis** [comment] 2015-09-22 15:32
I fixed the issue with the tile images not changing, it was to do with how I installed SuperTux.

Anyway, once I got the tiles working, I managed to modify each of the affected tiles to include one very transparent pixel, forcing GIMP to export it with a proper alpha channel.

It worked, the transparent backgrounds were back for the vines, and the goal tiles were the right colour.

Do I push the updated tile images as a quick fix, or should we look into why this is happening and try to fix it properly?

**Comment by tobbi** [comment] 2015-09-22 20:32
Yeah, please push them as a fix. I still think we need to investigate the root cause which might lie somewhere in SDL2.

**Comment by LMH0013** [comment] 2015-09-28 04:46
When images were first compressed a while back I noticed this as well- might have actually been before SDL2.  I had to regenerate the file using a RGB format to fix it.  Apparently I didn't make any noise about it, but whenever we compress image files we'll have to make sure the format doesn't change to avoid the bug.

**Comment by sydneyjd** [comment] 2015-09-30 21:06
@NNemesis Did you get Tobbi's message up there?
 Could you make a pull request with the fixed images? 

Thanks!!!!!

**Comment by NNemesis** [comment] 2015-10-03 11:40
Sorry for the delay guys, I pushed the fixed images in this pull request: https://github.com/SuperTux/supertux/pull/169

**Comment by tobbi** [comment] 2015-10-05 23:01
This has been fixed on master, closing. Thanks NNemesis.

**Closed by tobbi** 2015-10-05 23:01 UTC
Labels: priority:high, type:bug
