### ISSUE TITLE
SuperTux not opening on Fedora 36

### ISSUE THREAD

**Issue by discover02** [SuperTux/supertux#2160] opened 2022-03-06 15:48 UTC
**SuperTux version:**
0.6.2 and 0.6.3

**System information:** *(details about your kernel, operating system, or distribution)*
OS: Fedora 36
DE: Gnome 42
Kernel: Xanmod 5.16.12
CPU: Intel 10105F
GPU: Sapphire Radeon R7 240
RAM: 8GB
GPU Kernel Driver: amdgpu

##### Expected behavior
![image](https://user-images.githubusercontent.com/62564400/156930375-19152121-e054-4f3d-87e7-580ce2da7c24.png)

**Comment by discover02** [comment] 2022-03-06 15:50
- I cleaned old config files. (~/.local/share/supertux2)
- I tried other users.
- I tried development version, steam version and default version. But not work.

**Comment by Semphriss** [comment] 2022-03-06 15:58
Can you try downloading a Debug build and running it in a debugger? This will be easier to see where it gets stuck.

**Comment by discover02** [comment] 2022-03-06 16:06
> Can you try downloading a Debug build and running it in a debugger? This will be easier to see where it gets stuck.

![image](https://user-images.githubusercontent.com/62564400/156931291-4cd0b5d7-d814-4d46-9b0b-78970fbadd1f.png)

**Comment by Semphriss** [comment] 2022-03-06 16:11
Try hitting Ctrl+C to bring up the debugger and make it print a backtrace, to see where it is in the code.

**Comment by discover02** [comment] 2022-03-06 16:29
> Try hitting Ctrl+C to bring up the debugger and make it print a backtrace, to see where it is in the code.

How can i open debugger mode?

**Comment by Semphriss** [comment] 2022-03-06 16:30
You need to run it in a debugger, like `gdb`.

**Comment by discover02** [comment] 2022-03-06 16:32
> > Can you try downloading a Debug build and running it in a debugger? This will be easier to see where it gets stuck.
> 
> ![image](https://user-images.githubusercontent.com/62564400/156931291-4cd0b5d7-d814-4d46-9b0b-78970fbadd1f.png)

This is gdb

**Comment by Semphriss** [comment] 2022-03-06 16:34
This isn't gdb. gdb is invoked by calling it with the executable name as argument, like `gdb ./supertux`, rather than piping the stdout of the game into it (which gdb can't do anything with).

**Comment by discover02** [comment] 2022-03-06 16:35
> This isn't gdb. gdb is invoked by calling it with the executable name as argument, like `gdb ./supertux`, rather than piping the stdout of the game into it (which gdb can't do anything with).

![image](https://user-images.githubusercontent.com/62564400/156932469-623368c1-49a1-44c9-834e-af2d1abaad3c.png)

**Comment by discover02** [comment] 2022-03-06 16:36
![image](https://user-images.githubusercontent.com/62564400/156932507-407e34eb-dd2c-495d-911f-129305110981.png)

**Comment by discover02** [comment] 2022-03-06 16:36
> > > Can you try downloading a Debug build and running it in a debugger? This will be easier to see where it gets stuck.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/62564400/156931291-4cd0b5d7-d814-4d46-9b0b-78970fbadd1f.png)
> 
> This is gdb

2

**Comment by Semphriss** [comment] 2022-03-06 16:39
My bad - first time I see a terminal display it like that.

Try compiling SuperTux from source; pass `-DCMAKE_CXX_FLAGS=-ggdb` while invoking cmake, and invoke the debugger on the compiled version.

**Comment by discover02** [comment] 2022-03-06 16:46
Okay, I'll let you know after I try it. Thanks

**Comment by discover02** [comment] 2022-03-06 21:18
![image](https://user-images.githubusercontent.com/62564400/156942616-2e117d49-de9f-4e21-98e7-c10c4b81481e.png)

**Comment by Semphriss** [comment] 2022-03-06 21:34
What compiler are you using? SuperTux is tested against GCC 9.3.0+ and Clang 11+.

**Comment by discover02** [comment] 2022-03-06 21:37
> What compiler are you using? SuperTux is tested against GCC 9.3.0+ and Clang 11+.

![image](https://user-images.githubusercontent.com/62564400/156943158-bb9550d3-8d85-4fa8-853f-4d793a657e86.png)

**Comment by Semphriss** [comment] 2022-03-06 21:40
Odd. Try with the other compiler?

**Comment by Semphriss** [comment] 2022-03-06 21:40
Alternatively, you can do the fix GCC recommends.

**Comment by discover02** [comment] 2022-03-06 21:49
> What compiler are you using? SuperTux is tested against GCC 9.3.0+ and Clang 11+.



> Odd. Try with the other compiler?

How it? I typing;
cmake .. -DCMAKE_CXX_FLAGS=-ggdb
make

**Comment by Semphriss** [comment] 2022-03-06 21:57
Have a look at the [documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER.html).

**Comment by discover02** [comment] 2022-03-07 04:03
`cmake .. -DCMAKE_CXX_FLAGS=-ggdb -DCMAKE_C_COMPILER="clang"`

![image](https://user-images.githubusercontent.com/62564400/156965877-ddbee7c5-4839-46f7-8dc1-adcf890b95fe.png)

**Comment by Semphriss** [comment] 2022-03-07 05:27
Submodules are improperly checked out. Please follow the instructions as written [here](https://github.com/SuperTux/supertux/blob/master/INSTALL.md#linuxunix-using-cmake).

**Comment by Semphriss** [comment] 2022-03-07 05:55
Btw, Fedora 36 isn't released yet. SuperTux can't reasonably be expected to work in environments that don't provide a minimum of stability. I tested the release AppImage on the latest release of Fedora (35) and it works fine; if you wish to play SuperTux, I recommend you either stay on 35 until 36 is stable, or that you wait until 36 is stable, or that your report the bug to Red Hat developers to see if the issue is in Fedora.

If you wish to continue trying to debug with compiling, I recommend you first familiarize with the compilation process. Although I'm happy to help, I'm afraid the time I can devote to technical support is limited, and I won't always be there to help you. You can join the numerous community chats listed in the [README](https://github.com/SuperTux/supertux#community) if you wish to receive help from the community.

I'm closing this issue since the problem is (most likely) not on the SuperTux side. However, that does not mean that I stop watching this thread altogether; I'll still be there to help you if you need it. But my activity might be less regular, and chats should be the privileged option.

**Closed by Semphriss** 2022-03-07 05:55 UTC
Labels: os:linux

**Comment by discover02** [comment] 2022-03-07 07:26
But the real problem is this. I've been using Fedora 36 for a long time. SuperTux was running smoothly. This issue has been occurring for about 1 week.

**Comment by discover02** [comment] 2022-03-07 08:09
AL lib: (EE) ALCpulsePlayback_connectStream: Stream did not get ready: Timeout
[WARNING] /home/runner/work/supertux/supertux/src/audio/sound_manager.cpp:65 Couldn't initialize audio device: Couldn't open audio device.

**Comment by discover02** [comment] 2022-03-07 08:26
I installed SuperTux flatpak version. And i disable pulseaudio support. Problem solved. I think it's an issue with the sound server. The same sound server version is also available in fedora 35. The same issue would occur if I used it on Fedora 35.

![image](https://user-images.githubusercontent.com/62564400/156994487-ba16253e-82f2-43d0-8b4f-b0fb067fbf19.png)
