### ISSUE TITLE
Carrying a ticking bomb and then coliding with a bad guy, sets off the bomb hurting Tux

### ISSUE THREAD

**Issue by n3rdopolis** [SuperTux/supertux#1160] opened 2019-08-31 17:32 UTC
If you carry a Mr Ice Block and collide with a bad guy, it kills both the Mr Ice Block, and the bad guy.

If you carry a ticking Mr Bomb and collide with a bad guy, the bonus kills the bomb and the bad guy, but Tux gets hurt in the explosion.

However, I don't think a bonus like that should ever hurt Tux. (I could be wrong).
If you are able to grab a falling skydive out of the air, and collide with a bad guy, they both die without the Skydive hurting Tux.

**Comment by HybridDog** [comment] 2019-10-27 09:25
I think this behaviour is intended. It is also possible to throw up a rock and walk under it, and when it falls down, Tux gets hurt.

**Comment by HybridDog** [comment] 2019-11-06 08:31
I'm not sure about the Skydive; maybe it should explode and hurt Tux when he walks into an enemy.

**Comment by Semphriss** [comment] 2022-01-24 15:46
Closing as intended behavior.

**Closed by Semphriss** 2022-01-24 15:46 UTC
Labels: wontfix
