### ISSUE TITLE
Haywire doesn't stop making noises when offscreen

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1325] opened 2020-01-22 05:22 UTC
**SuperTux version: 0.6.1**
**System information:** *Windows 10*

##### Expected behavior
If you ignite a Haywire and then it goes offscreen before it can explode the growling sound stops

##### Actual behavior
It doesn't stop

##### Steps to reproduce actual behavior
Have an ignited Haywire go offscreen

**Comment by weluvgoatz** [comment] 2020-01-22 05:25
Duplicate of #1260. Closing.

**Closed by weluvgoatz** 2020-01-22 05:25 UTC
