### ISSUE TITLE
SuperTux window show only background gradient on start under Windows 7

### ISSUE THREAD

**Issue by Symbian9** [SuperTux/supertux#1084] opened 2019-04-02 12:29 UTC
**SuperTux version:** 0.6.0 (release)
**System information:** *Windows 7, 32-bit*

##### Expected behavior

Show main menu

##### Actual behavior

Only background gradient is visible on SuperTux start

![pic.1](https://i.imgur.com/2s69b0x.png)

##### Steps to reproduce actual behavior

1. Install SuperTux v.0.6.0 (32-bit release build);
2. Start SuperTux.

**Comment by tobbi** [comment] 2019-04-02 15:12
Are your graphics drivers up-to-date?

**Comment by tobbi** [comment] 2019-08-06 16:37
Closing due to lack of response.

**Comment by tobbi** [comment] 2019-09-03 20:44
We have another user with this problem, so I'll re-open. 

@Grumbel Do you have any idea what could be happening here?

**Comment by tobbi** [comment] 2020-01-02 13:47
@Symbian9 Can you see whether the issue is fixed with 0.6.1 ?

**Comment by Symbian9** [comment] 2020-01-02 14:08
Now I has no access to this Windows PC. So, sorry, can't test it anymore.

**Comment by tobbi** [comment] 2020-01-06 15:46
I'm going to close this issue. Should it occur again, it can get reopened.

**Closed by tobbi** 2020-01-06 15:46 UTC
