### ISSUE TITLE
Music from "picnic with penny" overlaps with the music tux dances to

### ISSUE THREAD

**Issue by Dugglez** [SuperTux/supertux#347] opened 2016-01-29 09:44 UTC

**Comment by tobbi** [comment] 2016-01-29 10:53
@SuperTux/developers Is this intended behaviour or a bug?

**Comment by Hume2** [comment] 2016-01-29 11:20
I think that this is intended. Firstly, those two musics don't interfere themselves, so they can be well determinated. Secoundly, the music from the radio doesn't sound well enough to be played solo IMO.

**Comment by tobbi** [comment] 2016-01-29 11:40
What we could do, however, is to lower the volume of the background music when the radio is played. Do we have a scripting interface for that?

**Comment by Hume2** [comment] 2016-01-29 11:47
That's possible. We don't have the scripting interface for that.
I just wanted to say that that music from the radio is there just for that people could recognize that the radio is playing, not an actual music. However, I'm not the right one to say that, so it could be another way.

**Comment by brmbrmcar** [comment] 2016-01-29 15:41
I think it should still remain the same.

**Comment by brmbrmcar** [comment] 2016-01-29 15:42
Lowering the music would probably sound more awful than muting it all together.

**Comment by Karkus476** [comment] 2016-01-30 22:40
It's a minor thing, but still well worth considering

**Comment by Rusty-Box** [comment] 2019-11-17 14:25
This will most likely remain unchanged. Having the "Tux rap" play on its own in the intro cutscene sounds odd. I am closing this.

**Closed by Rusty-Box** 2019-11-17 14:25 UTC
Labels: category:levels, priority:low, status:needs-discussion

**Comment by qwertychouskie** [comment] 2019-11-18 18:44
IMO the main music should at least have its volume reduced.  I've always noticed this issue and it IMO sounds really bad to have two different songs playing at once.
