### ISSUE TITLE
In the options menu, give an option to switch between monitors in a multi-monitor setup

### ISSUE THREAD

**Issue by FrankAbagnaleJr** [SuperTux/supertux#660] opened 2016-12-07 04:02 UTC
**SuperTux version:** 0.5.1
**System information:** Windows 10 Pro x64 Version 1607 Build 14393.447

##### Expected behavior
A way to switch to my TV "monitor" for couch gaming

##### Actual behavior
No such option apparent

##### Steps to reproduce actual behavior

Edit: For clarity, I mean all of this in the context of fullscreen mode

**Comment by maxteufel** [comment] 2016-12-10 08:42
This sounds like a problem with Window's [window manager](https://en.wikipedia.org/wiki/Window_manager), not something SuperTux nor any other application (besides the window manager) should mess around with.

**Comment by maths22** [comment] 2016-12-10 18:44
@FrankAbagnaleJr Is this an issue when you are running full-screen or when you are running in windowed mode

@maxteufel If the issue is in windowed mode, you are correct, it would be a window manager issue.  If it is an issue in full-screen mode, that probably requires further investigation

**Comment by FrankAbagnaleJr** [comment] 2016-12-10 19:18
@maths22 This is in fullscreen. Some programs have a setting labeled something like "target monitor" to change which monitor is used in fullscreen, and that's what I was looking for.

**Comment by tobbi** [comment] 2016-12-10 19:20
This is something that needs to be worked on. SDL has a setting for this.

**Comment by maxteufel** [comment] 2016-12-10 20:03
> @maxteufel If the issue is in windowed mode, you are correct, it would be a window manager issue. If it is an issue in full-screen mode, that probably requires further investigation

It's still the window manager that handles (should handle) full-screen. It's just a flag for a specific window.

**Comment by tobbi** [comment] 2016-12-10 23:36
I have started this in #663

**Comment by tobbi** [comment] 2018-12-08 22:44
Closing as per https://github.com/SuperTux/supertux/pull/663#pullrequestreview-12363347

**Closed by tobbi** 2018-12-08 22:44 UTC
Labels: category:code, involves:functionality, priority:medium, status:needs-discussion, status:needs-work, type:feature
