### ISSUE TITLE
incorporate multiplayer

### ISSUE THREAD

**Issue by charla-con-galo** [SuperTux/supertux#1482] opened 2020-07-27 15:43 UTC
It would seem interesting to me that a multiplayer similar to that of mario maker 2 is incorporated, with competitive and cooperative mode, as I know that online is complex, it could only be local multiplayer. and although it could be 2 or 4 players, 6 or even 8 players would seem better.

**Comment by Alzter** [comment] 2020-08-01 04:30
I believe multiplayer was worked on at some point but it's still very incomplete, seems unlikely it'll be added in the foreseeable future

**Comment by charla-con-galo** [comment] 2020-08-01 15:47
It is probable, and although the fact that the game is in an incomplete phase to add multiplayer is very true, it would seem very interesting for the future.

**Comment by Zwatotem** [comment] 2020-08-12 10:55
Duplicate of #224. The other one has already a lot of discussion, and more details. Closing.

**Closed by Zwatotem** 2020-08-12 10:55 UTC
Labels: duplicate
