### ISSUE TITLE
Idea for level editor: Camera zoom in and out.

### ISSUE THREAD

**Issue by jojocarlos** [SuperTux/supertux#2655] opened 2023-10-06 14:30 UTC
It's just an idea that could improve the level editor experience (but can be discarded if it's not good). 
I think the editor could have a function to **zoom in and out** of the level view, so they could capture a better view of the level seen from afar.

"I don't know if I should put the idea here or somewhere else."

**Comment by Alasdairbugs** [comment] 2023-11-13 16:45
duplicate of #2421

**Closed by Alasdairbugs** 2023-11-13 16:45 UTC
Labels: involves:editor, type:idea, category:code, status:needs-work
