### ISSUE TITLE
Errors in the tiles.strf file

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#423] opened 2016-05-23 18:52 UTC
I accidentally messed up the tiles.strf file with my "Forest improvements" commit. I'm a bit too busy to make a pull request right now, but I've attached a fixed version that actually works.
[tiles.zip](https://github.com/SuperTux/supertux/files/278053/tiles.zip)

**Comment by tobbi** [comment] 2016-05-24 10:55
Is this a duplicate of Supertux/data#9 ?

**Comment by brmbrmcar** [comment] 2016-05-24 14:39
It was designed to fix this issue.

**Comment by maxteufel** [comment] 2016-05-29 16:42
Fixed by SuperTux/data#9 or SuperTux/data@d637b48210839796f078ee4cecd8fec80ca597c1.

**Closed by maxteufel** 2016-05-29 16:42 UTC
