### ISSUE TITLE
Bug Report: Unreadable/Unintelligible Options in the Game

### ISSUE THREAD

**Issue by xingwozhonghua126** [SuperTux/supertux#2762] opened 2024-02-03 11:52 UTC
SuperTux version: 0.6.3
System information: Arch Linux (kernel version 5.10.10-arch1-1)

Expected behavior
In the game, the options should be displayed correctly in Chinese so that I can understand and select them. The mouse movement speed should be consistent between in-game and outside the game, without any delay.

Actual behavior
In the game, all the options are displayed as question marks, making it impossible to understand and select them. The mouse movement inside the game has a noticeable delay compared to the mouse movement outside the game.

Steps to reproduce actual behavior
Launch SuperTux.
Navigate to the options menu.
Observe that the options are displayed as question marks.
Move the mouse inside the game and notice the delay in mouse movement compared to outside the game.

Dear [Game Developers],

I hope this message finds you well. I am writing to bring to your attention a rather frustrating issue I encountered while playing your game. It appears that all the options within the game interface are displayed as question marks (???), rendering them completely unreadable and making it impossible to make informed choices.

This bug has severely impacted my overall gaming experience, as it prevents me from progressing further or making decisions that may affect the outcome of the game. Without being able to understand the meaning or context behind each option, it becomes exceedingly difficult, if not impossible, to fully engage with the gameplay.

I have attempted to troubleshoot this issue on my own, but unfortunately, I have been unsuccessful in rectifying the problem. I have checked for any software updates, cleared the cache, and even reinstalled the game, all to no avail.

To provide you with additional context, I am running the game on a [mention operating system/version], on a [mention device model/version]. Additionally, I have not experienced any similar issues with other games or applications on my device, indicating that the problem is specific to your game.

I kindly request your assistance in resolving this bug promptly, as it significantly compromises the usability and enjoyment of the game. I understand that troubleshooting such issues can be complex, and I am more than willing to provide any additional information or perform any necessary steps to help diagnose the problem.

Thank you in advance for your attention to this matter. I greatly appreciate your dedication to delivering a seamless gaming experience and believe that with your expertise, this bug can be successfully addressed, allowing players to fully immerse themselves in the world you have created.

Sincerely,
Carl

**Comment by xingwozhonghua126** [comment] 2024-02-03 12:27
https://download.supertux.org/

There is nothing wrong with it, but there is something wrong with it in the arch source.

**Comment by tulpenkiste** [comment] 2024-02-03 12:44
Reproduced on stable 0.6.3-7, cannot reproduce on nightly 0.6.3-953-g52c367e97
![image](https://github.com/SuperTux/supertux/assets/63363329/0addb2f2-1a36-4447-b80d-fd21267e2439)

**Comment by tulpenkiste** [comment] 2024-02-03 12:50
Simple reproduce steps:
1. open terminal
2. `LANG=zh_CN.UTF-8 supertux2 # or app image, non UTF-8 locale works as well)`
3. wait for title screen to load

**Comment by mrkubax10** [comment] 2024-02-03 12:59
Fixed in 30ce107. For now use the development version.

**Closed by mrkubax10** 2024-02-03 12:59 UTC
