### ISSUE TITLE
Level starting as Air/Earth Tux bug

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#400] opened 2016-04-08 10:30 UTC
When starting a level as Air Tux, it shows as big Tux at the level screen at the start, and Earth Tux shows as Little Tux.

**Comment by tobbi** [comment] 2016-04-09 12:37
The issue is that earth and air are only hats which get added atop of the sprite.

**Comment by brmbrmcar** [comment] 2016-04-09 15:22
That is what I thought the issue was. But it is unusual for one to end up small Tux and the other large.

**Comment by tobbi** [comment] 2016-04-09 15:23
No, because one case was not added to the switch method, which was fixed by the above commit. For the other thing, I need to do some more magic.

**Comment by tobbi** [comment] 2016-04-09 15:28
Also, please change the issue label to reflect the changes.

**Comment by brmbrmcar** [comment] 2016-04-09 15:41
Did you mean that?

**Comment by tobbi** [comment] 2016-04-09 15:42
Yes. Thanks.

**Closed** 2016-04-11 15:22 UTC
