### ISSUE TITLE
Graphics bugs

### ISSUE THREAD

**Issue by Kracksu** [SuperTux/supertux#1917] opened 2021-12-03 18:47 UTC
I have a problem in super tux, when i start the game the graphics are dark and the sky are blue
Here i send a screenshot
![Captura de pantalla (15)](https://user-images.githubusercontent.com/95499830/144656524-5dfc066c-5350-4dcc-8fb9-c6157368cc9b.png)

**Comment by Semphriss** [comment] 2021-12-03 19:40
Same issue: #1531 #1667
Related issues: #1397 

Please see these issues and try some fixes. Some I have on my mind right now:
- Are your graphic drivers up-to-date? If yes, what GPU do you use?
- Try running the game with the SDL renderer, throught the command line with `supertux2.exe --renderer sdl` or by editing the config file located at `C:\Users\[you]\AppData\Roaming\SuperTux\supertux2\config` and changing `(renderer "[...]")` to `(renderer "sdl")`

**Comment by Kracksu** [comment] 2021-12-03 20:18
But with what program i open the config file

**Comment by Semphriss** [comment] 2021-12-03 22:06
Notepad, or any text editor. The file is an ordinary text file, it just lacks the `.txt` extension. You may have to select Notepad manually when opening ité

**Comment by mrkubax10** [comment] 2021-12-10 07:49
This is duplicate of that issue

**Comment by Semphriss** [comment] 2021-12-27 22:59
Given that this is a duplicate and that this issue brings nothing new, I'll close it in favor of the other one.

**Closed by Semphriss** 2021-12-27 22:59 UTC
Labels: duplicate, common-issues:broken-graphics
