### ISSUE TITLE
Tux Is at the Wrong Level on the World Map

### ISSUE THREAD

**Issue by jumpball** [SuperTux/supertux#72] opened 2015-05-14 13:20 UTC
I installed Supertux 0.3.5a and opened it. Tux wasn´t on the first level, he was between the fourth and the fifth level and all levels weren´t done.

**Comment by sydneyjd** [comment] 2015-05-20 04:21
Issue with the config...
@jumpball What OS are you running?

**Comment by pazkero** [comment] 2015-06-27 00:09
Based on Supertux 0.3.4 playthough, I may assume that you already played this game before, @jumpball ?

**Comment by Karkus476** [comment] 2015-09-04 12:40
On linux, if you run make install (and play the game a bit)then run make again then you will be wherever you got to in your previous playthrough, but with no levels completed

**Comment by brmbrmcar** [comment] 2015-09-20 19:50
Same on 0.4.0.

**Comment by sydneyjd** [comment] 2015-09-21 01:42
Please clear your Supertux config file. Its usually .supertux2 or something similar.

**Comment by tobbi** [comment] 2015-09-21 07:54
We should find a way to prevent that from happening. Not sure how to do it, though.

**Comment by sydneyjd** [comment] 2015-09-24 16:00
This is not really an issue, its something that needs to be known about though.

**Comment by tobbi** [comment] 2015-09-24 16:04
Ideally, this should be fixed properly.

**Comment by brmbrmcar** [comment] 2015-09-24 16:18
Aren't there similar ways of automatically spawning Tux? (Different code). We should try that.

**Comment by Karkus476** [comment] 2015-10-08 17:48
If you reinstall supertux after completing a few levels, this happens. I think.

**Comment by Karkus476** [comment] 2015-10-08 20:51
@jumpball @brmbrmcar can you give us any ideas on when and why this might happen? If you messed with the config this is not an issue. If no reply is gotten, or no one else can replicate this, it will be closed.

**Comment by Karkus476** [comment] 2015-10-27 18:18
We actually need to work out what the issue is: Why has tux's position not been reset, when the worldmap has? Rather than just a hack which tests if it's a possible map situation

**Comment by brmbrmcar** [comment] 2015-10-27 18:22
It doesn't happen when the worldmap resets necessarily.

**Comment by Karkus476** [comment] 2015-10-27 18:23
@brmbrmcar I think it happens when you reinstall supertux

**Comment by brmbrmcar** [comment] 2015-10-27 18:30
Yes, it does.

**Comment by tobbi** [comment] 2015-10-30 00:22
I believe what happens is that it reads Tux's position from the squirrel table which seems to succeed, but fails to read the level information. Since tux's position has already been set, but the subsequent call to get the level tables yields an error, this leads to the situation above.

**Comment by Karkus476** [comment] 2015-10-30 13:28
This is not yet tested. Did you close it intentionally?

**Comment by tobbi** [comment] 2015-10-30 14:13
You're right, it should be tested. I kind of closed it intentionally because I figured this might be the only reason why this happens. But, someone go ahead and test it.

**Comment by brmbrmcar** [comment] 2015-10-30 14:16
It is going to take forever to test; the issue is random.

**Comment by Karkus476** [comment] 2015-10-30 21:05
Install, and then reinstall SuperTux. I believe that causes the problem

**Comment by brmbrmcar** [comment] 2015-10-30 21:08
Sometimes.

**Comment by Karkus476** [comment] 2015-11-09 16:46
Okay, to save space I'll close this. But if another issue is made about it, we will close that and open this.

**Closed by Karkus476** 2015-11-09 16:46 UTC
Labels: category:code, involves:functionality, status:needs-information

**Comment by brmbrmcar** [comment] 2015-11-09 16:48
Bad idea.

**Comment by Karkus476** [comment] 2015-11-09 16:49
@brmbrmcar Why?

**Comment by brmbrmcar** [comment] 2015-11-09 16:51
Because the issue may still be there. Closed = resolved.

**Comment by brmbrmcar** [comment] 2015-11-09 16:51
Is it resolved?

**Comment by Karkus476** [comment] 2015-11-13 20:56
@brmbrmcar Yes. If it occurs again I will edit this comment.

**Comment by brmbrmcar** [comment] 2015-11-13 20:58
That is not resolved. That is "ah, noone has mentioned it yet".

**Comment by Karkus476** [comment] 2015-11-13 21:04
@brmbrmcar I admire your persistance. Please feel free to replicate this issue (on the latest code) and reopen this with evidence

**Comment by brmbrmcar** [comment] 2015-11-13 21:05
I would, but how?

**Comment by brmbrmcar** [comment] 2015-11-13 21:06
Oh. Latest builds.
