### ISSUE TITLE
Game crashes when Mr Bomb explodes

### ISSUE THREAD

**Issue by symvizan** [SuperTux/supertux#725] opened 2017-08-01 09:08 UTC
**SuperTux version:** latest
**System information:** *(details about your kernel, operating system, or distribution)*ú
Windows 7

##### Expected behavior
Mr Bomb explodes

##### Actual behavior
When Mr Bomb would explode the game crashes

##### Steps to reproduce actual behavior
Jump on Mr Bomb and wait until he explodes

##### Additional debugging information
Unhandled exception at 0x000000000BF31D07 (Sens_oal.dll) in supertux2.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by tobbi** [comment] 2017-08-01 09:58
This is likely caused by some kind of outdated OpenAL driver. We do package SuperTux with the OpenAL libraries, however, I don't know the location of pre-built DLLs that you could use to replace stuff with.

**Comment by tobbi** [comment] 2017-08-01 10:00
Ah, here we go:
Can you download the binaries from http://kcat.strangesoft.net/openal-binaries/openal-soft-1.18.1-bin.zip and replace the ones you can find in SuperTux's application directory with those you downloaded?

**Comment by symvizan** [comment] 2017-08-02 08:32
I can't find the openal drivers in the SuperTux root folder. There is bin, data, doc, share, supertux.ico, supertux.png

**Comment by maxteufel** [comment] 2017-08-02 08:34
Check out the bin folder.

**Comment by symvizan** [comment] 2017-08-02 08:37
In the bin folder I can't find a folder called openal-soft-1.18.1-bin which I can replace with the one I downloaded.

**Comment by maxteufel** [comment] 2017-08-02 08:38
In your `openal-soft-1.18.1-bin` folder there should be some `dll` files. Copy them over in the `bin` folder.

**Comment by symvizan** [comment] 2017-08-02 08:40
There are no dll files in openal-soft-1.18.1-bin. It has however a bin folder inside of it, which has two more folders in it win32 and win64. Each of them has a soft_oal.dll inside of it.

**Comment by maxteufel** [comment] 2017-08-02 08:41
If you installed 64-bit SuperTux, you take the dll from the win64 folder, if you installed 32-bit SuperTux, take the win32 dll.

**Comment by symvizan** [comment] 2017-08-02 08:43
Still crashes. Tryed with them both. By the way in the SuperTux bin folder there was no soft_oal.dll already, only the one I have dragged in.

**Comment by symvizan** [comment] 2017-09-16 16:20
The supertux directory and the openal folder differ in structure and files.

**Comment by tobbi** [comment] 2017-10-03 09:51
Did you find a sens_oal.dll in any of the downloaded files and/or SuperTux directories?

**Comment by symvizan** [comment] 2017-10-23 17:58
I have since reinstalled my Operating system due to other reasons and I am yet to test if it works on this install. BTW I am still using Windows 7.

**Comment by busybody42** [comment] 2018-03-21 01:16
RUSTY BOX?!?! DID YOUR COUSIN EXPLODE THE GAME AGAIN?!?!  sorry, haywire

**Comment by busybody42** [comment] 2018-05-26 20:11
But really, does it also crash when haywires or gold bombs explode?

**Comment by tobbi** [comment] 2018-05-30 23:04
I'm gonna close this issue since in any case, it wouldn't be our bug, but a bug in OpenAL.

Please re-open, should you ever run into the same problem.

**Closed by tobbi** 2018-05-30 23:04 UTC
