### ISSUE TITLE
Unable to change sprite of trampoline

### ISSUE THREAD

**Issue by Hume2** [SuperTux/supertux#2705] opened 2023-12-21 08:16 UTC
**SuperTux version:** latest GIT
**System information:** unimportant

##### Expected behavior
When I set the property sprite of a trampoline to something else, I see a different sprite.

##### Actual behavior
I see the default sprite anyway.

##### Steps to reproduce actual behavior
Create a level, add a trampoline, change the sprite to something else and play the level. The sprite will change in the editor but not after you launch the level.

##### Additional debugging information

Do this ASAP lol

**Comment by Vankata453** [comment] 2023-12-21 08:46
Duplicate of #2701.

**Closed** 2023-12-21 08:46 UTC
