### ISSUE TITLE
Inform players about update

### ISSUE THREAD

**Issue by Zwatotem** [SuperTux/supertux#1225] opened 2019-11-25 13:17 UTC
**SuperTux version:** All until 0.6.1 beta1
**System information:** *not inportant*

##### Expected behavior
Game shows a popup on startup or a menu position, if there is new version of the game available.

##### Actual behavior
To know if there is a new version player must regularly check the official webpage or Github

##### Proposed solution
Make the game on every startup run a funtion, that contects to a server and checks if there is new version for download. If there is it shows additional option in main menu, which redirects to apropriate subpage of supertux.org for download.

I know this may not be trivial, but it would be good if it got to the game yet in 0.6.1. I think a lot of code can be reused, since we already have addon manager, or donate button. And it's more logical to add it now, than in some major release, since it's purpose is not to miss major features.

**Comment by Zwatotem** [comment] 2019-11-25 13:18
BTW I would do it myself, but I cannot do web stuff.

**Comment by tobbi** [comment] 2019-12-08 23:51
Duplicate of #248 ?

**Comment by Zwatotem** [comment] 2019-12-09 18:37
Oh... I didn't notice that. Sorry.

**Comment by Ordoviz** [comment] 2020-05-13 10:35
This issue should be closed.

**Comment by tobbi** [comment] 2020-05-13 11:12
Closed as a duplicate of #248.

**Closed by tobbi** 2020-05-13 11:12 UTC
