### ISSUE TITLE
Game fails to load

### ISSUE THREAD

**Issue by Jeffry84** [SuperTux/supertux#512] opened 2016-07-29 14:30 UTC
**SuperTux version:**
Latest Nightly build (0.4.0.788)

**System information:**
Debian Stable Xfce, all vanilla except this repo

##### Expected behavior
Game starting.
It did before, so to clarify that it's a program issue and not a pc issue.

##### Actual behavior
It fails to load with the message: "[WARNING] /usr/src/packages/BUILD/src/supertux/main.cpp:188 Couldn't add 'share/games/supertux2' to physfs searchpath: not found
[FATAL] /usr/src/packages/BUILD/src/supertux/main.cpp:510 Unexpected exception: Couldn't open 'images/engine/icons/supertux-256x256.png': not found"

##### Steps to reproduce actual behavior
Launch the game from a terminal
$ supertux2 (no other options)

*Edit (@maxteufel, 2016-07-29 16:33 UTC+2): removed task list containing guidelines*

**Comment by maxteufel** [comment] 2016-07-29 14:41
This is a known issue. Thanks for reporting it here.

It was most likely caused by @maths22's recent changes to the code that's supposed to find the data directory (#481).

This happens because the fallback mechanism, which is used when not running inside the build directory or when the source data directory doesn't exist, attempts to use CMake's `${INSTALL_SUBDIR_SHARE}`, which, by default, is defined to `share/games/supertux2`. As you may notice, this doesn't actually include any prefix where the game's supposed to look for.

The hackish, quick solution to this would be including `${CMAKE_INSTALL_PREFIX}` in `${INSTALL_SUBDIR_SHARE}`. I assume the less hackish fix to be using `SDL_GetBasePath()` again.

**Comment by maxteufel** [comment] 2016-07-29 14:44
Temporary workarounds (this should be fixed soon, though):

- Point the game to the correct data directory using the `--datadir` command line option
- Run the game in its installation prefix

**Comment by maths22** [comment] 2016-07-29 15:28
Fixed in 114ce5b.  (For some silly reason we were using datadir where we should have used basepath, but it happened to work with the old program logic)

**Closed by maths22** 2016-07-29 15:28 UTC
Labels: category:code, involves:functionality, priority:high, status:needs-work, type:bug
