### ISSUE TITLE
Spring requires 2 jumps to bounce high

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1037] opened 2019-01-09 22:14 UTC
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
If you hold jump button while falling onto a spring, you should jump very high.

##### Actual behavior
You jump normally. To actually use the spring's jump boost, you have to land on it again without touching the ground midway, holding the jump button.

##### Steps to reproduce actual behavior
Fall onto a spring while holding jump button.

**Comment by tobbi** [comment] 2019-01-16 19:34
I can't reproduce the issue here. Can anyone else?

**Comment by HybridDog** [comment] 2019-03-11 15:08
Maybe it's related to 1069.

**Comment by weluvgoatz** [comment] 2019-11-15 22:05
Perhaps this is intentional behaviour?

**Comment by Rusty-Box** [comment] 2019-11-15 22:07
I don't think so. But if, then this is not really ideal.

**Comment by Semphriss** [comment] 2020-12-23 03:10
Since nothing happens here, I'm gonna close it...

**Closed by Semphriss** 2020-12-23 03:10 UTC
Labels: status:needs-confirmation
