### ISSUE TITLE
Backflipping to a bonus block hides Tux behind it

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#201] opened 2015-10-24 09:42 UTC
![screenshot from 2015-10-24 10 41 59](https://cloud.githubusercontent.com/assets/14400196/10710014/e33f3e20-7a3b-11e5-833e-8c76f356939e.png)

**Comment by maxteufel** [comment] 2015-10-24 09:43
Should this considered to be a bug or a feature?

**Comment by brmbrmcar** [comment] 2015-10-24 09:44
Feature; it isn't massive.

**Comment by maxteufel** [comment] 2015-10-24 09:47
Then, where's the issue?

**Comment by brmbrmcar** [comment] 2015-10-24 09:48
It's a bit of a bug.

**Comment by brmbrmcar** [comment] 2015-10-24 09:48
How can Tux get behind it?

**Comment by sydneyjd** [comment] 2015-10-25 01:39
Its a good thing to point out, but its honestly not a big deal, so if i hear no objections, i will close this issue.

**Comment by brmbrmcar** [comment] 2015-10-25 08:28
It's worse than https://github.com/SuperTux/supertux/issues/165.

**Comment by Hume2** [comment] 2015-10-25 15:06
How do you think that this should be fixed?

**Comment by Karkus476** [comment] 2015-10-26 20:22
@brmbrmcar I don't see what the problem is. Is it the fact that he's behind? That's not really a bug, let's be honest.

**Comment by tobbi** [comment] 2015-10-27 09:54
I'm sorry, I will close this. I know it might be considered a bug. But it's barely noticeable (only people who have *severe* OCD will notice this). To fix this, substantial resources would be needed, as far as I can tell...

**Comment by Mathnerd314** [comment] 2015-10-29 05:43
This is a hitbox bug, if you use ``debug_collrects(true)`` you will see that Tux's backflip hitbox has been messed up a lot by f8a53829ebdb72bd7deffa1d249b71625e84a10a. It's particularly noticeable if you're in a 1-block wide chute:
![image](https://cloud.githubusercontent.com/assets/322214/10811018/e13f047c-7dcc-11e5-94ff-c734fa4fdfea.png)
Tux's image is somewhat shifted to the left (his hitbox is exactly within the chute of course).

**Comment by brmbrmcar** [comment] 2015-10-29 08:44
I thought so.

**Comment by Karkus476** [comment] 2015-11-21 17:24
Here is a test level, with a chute and some item blocks to backflip into[backflip.stl.txt](https://github.com/SuperTux/supertux/files/40895/backflip.stl.txt)

**Comment by Karkus476** [comment] 2015-11-21 17:28
But the question is, is this intended behaviour? I still want to be able to backflip inside a chute, personally.

**Comment by tobbi** [comment] 2015-11-21 17:29
https://github.com/SuperTux/supertux/issues/201#issuecomment-152082545 -> This isn't intended behaviour.

**Comment by Karkus476** [comment] 2015-11-21 17:30
@tobbi Okay, what _is_ intended behaviour?

**Comment by tobbi** [comment] 2015-11-21 17:32
Basically, the hitbox needs to be changed to cover the rotated sprite...You can see that the hitbox has the form of standing bigtux.

**Comment by Karkus476** [comment] 2015-11-21 17:33
Okay.

**Comment by brmbrmcar** [comment] 2015-11-21 17:41
Oh yes. I have got the test level.

**Comment by brmbrmcar** [comment] 2015-12-07 21:34
http://www.fileconvoy.com/gf.php?id=g77c425f4f96b5358999757721.80632812ab44b1e00fe282&sts=144952397821742421685c52c9518e083addcb71b2d4a4b31dff (please re-upload somewhere else, will expire in 7 days)

**Comment by Karkus476** [comment] 2015-12-14 18:29
@Mathnerd314 @tobbi What do you suggest is done? How accurate should it be? (we don't want a rotating hitbox for example)
This is what debug_collrects showed me. It doesn't look like he's standing up, he's in fact still ducking.
![screenshot from 2015-12-14 18 27 45](https://cloud.githubusercontent.com/assets/14023329/11789831/7d073022-a290-11e5-8a16-2c0f9e0fb729.png)

**Comment by brmbrmcar** [comment] 2015-12-14 18:31
Wait there. I think Imight have something...
I'll just see. It probably will not work.

**Comment by brmbrmcar** [comment] 2015-12-14 18:41
And it does not.

**Comment by Mathnerd314** [comment] 2015-12-14 22:50
The problem is that it rotates around the center of the image, rather than the center of the hitbox: https://github.com/SuperTux/supertux/blob/ca101a9d356894276b6c7479325f42ba5c162e8e/src/video/gl/gl_painter.cpp#L67

I guess we could just change that.

**Comment by MCMic** [comment] 2015-12-30 03:52
This is not a bug IMO

**Comment by Karkus476** [comment] 2016-01-01 19:35
I agree with @MCMic , but believe we should do as @Mathnerd314 suggests to improve the look and feel of the backflip.

**Comment by Semphriss** [comment] 2021-01-02 21:11
Considering the sprites has changed and don't rotate anymore, I'll close this issue.

**Closed by Semphriss** 2021-01-02 21:11 UTC
Labels: category:code, type:bug
