### ISSUE TITLE
Occasional Glitch/Bug when Tux is hurt.

### ISSUE THREAD

**Issue by NikkOfTime** [SuperTux/supertux#303] opened 2015-12-28 17:08 UTC
So, I was playing 0.4.0 (Main levels), and I encountered a bug/glitch. I hit an enemy and this happened:
![glitch1](https://cloud.githubusercontent.com/assets/16466020/12022192/6ad47e48-ad42-11e5-8679-b751cf10e315.png)
Enemies still could walk just fine, and fireballs hit the ground just fine too.

**Comment by Karkus476** [comment] 2015-12-29 13:22
If possible, please provide a [recording]() to showcase the bug, or provide clearer steps to reproduce. (What do you mean by "hit" an enemy?)

**Comment by LMH0013** [comment] 2015-12-30 19:14
Almost looks like the wrong sprite is being displayed: like Tux is actually small, with the small Tux hitbox but the graphic being displayed is large Tux.  More info is definitely needed.  What powerup did you have prior to being hit?  Were you doing anything unique when it happened (such as backfliping)?  How were you hit?  Did the bug persist, or did it disappear once you moved?  Has the bug reoccurred or was it a one-time deal?  If it does repeat, a recording would answer all of these.  Most likely someone will have to reproduce the bug prior to fixing it.

**Comment by NikkOfTime** [comment] 2016-01-09 02:32
I had a fire helmet. What I meant by "hit" is got hurt by.

**Comment by Hume2** [comment] 2016-01-12 17:40
I think, it's the same bug as #321 .

**Comment by Karkus476** [comment] 2016-01-14 22:39
I agree it's similar, but not similar enough to close without conclusive evidence

- Karkus

**Comment by LMH0013** [comment] 2016-01-15 04:40
It's only similar in the fact that they both appear to be glitches in which sprite is displayed.  #321 is caused by the collision code still being run after a badguy has been neutralized but before the death animation is complete.  Whatever is happening here is something weird-- at least in the sense that it is difficult to reproduce.  I've had no luck, and would be interested if anyone has seen it other than this one case.

@NikkOfTime am I correct in assuming that Tux's movement was unhindered while half "submerged" in the ice (you could still move normally)?  Also, did the bug ever fix itself such as when you got another fire flower or after finishing/restarting the level?  I'd really be interested if you happened to try to backflip while the bug was occurring, if so how did that pan out?  I have a vague idea what might be happening, but no idea why.

**Comment by Hume2** [comment] 2016-03-24 20:00
It seems like O11c from the IRC has experianced this or similar bug, http://picpaste.com/supertux-bug-nMsoKZZ7.png .

**Steps to reproduce:** Play the level Countercurrent in Forest World.  Hit the spike just before, which does maks Tux flash, first Tux just fell through the ground by the spike, then Tux can't go back to the platform. It doesn't happen always.

In this glitched state, Tux can't jump, because he collides with the ground.

Correct me, if I didn't reinterpret it well.

**Comment by brmbrmcar** [comment] 2016-03-24 21:13
I cannot reproduce either bug.

**Comment by o11c** [comment] 2016-03-25 17:26
Note that I *can* crouch and backflip, despite the fact that I took damage and so should be small Tux.

**Comment by LMH0013** [comment] 2016-03-27 19:08
@brmbrmcar are you checking in the most recent build?  It could be that the fix for #332 has corrected the issue and it only appears in 0.4.0, thus you wouldn't be able to reproduce.  We would need someone to be able to reproduce in 0.4.0 but not be able to reproduce in the current code to confirm.  From what it sounds like, MiroslavR has probably fixed it, but we should probably get confirmation before closing the issue.

**Comment by LMH0013** [comment] 2016-03-27 19:10
I've also changed to Issue title to reflect that this is probably not related to any particular level.

**Comment by brmbrmcar** [comment] 2016-03-27 20:34
I am using 0.4.0.

**Comment by LMH0013** [comment] 2016-03-27 21:45
Bummer...  I thought we might have enough to figure this out.

**Comment by brmbrmcar** [comment] 2016-03-28 13:22
https://www.youtube.com/watch?v=etm_rHKNqJQ

**Comment by brmbrmcar** [comment] 2016-07-23 20:46
I had a glitch like this recently in a live stream when I dropped a block on myself in a level in Fiona's World.

**Comment by brmbrmcar** [comment] 2016-07-23 20:58
https://www.youtube.com/watch?v=DGqPW-u_Ylk is a video my glitch.

**Comment by maxteufel** [comment] 2017-05-15 17:18
Closing for now due to inactivity and needs-information status.

**Closed by maxteufel** 2017-05-15 17:18 UTC
Labels: status:needs-information, type:bug
