### ISSUE TITLE
Title bars in all apps disappear after opening SuperTux

### ISSUE THREAD

**Issue by knuxfanwin8** [SuperTux/supertux#803] opened 2018-04-17 18:07 UTC
**SuperTux version:** 0.5.1-8
**System information:** Fedora 27, kernel version 4.15.15-300.fc27.x86_64, KDE Plasma version: 5.12.4, KDE Frameworks version: 5.44.0

##### Expected behavior
Title bars in opened applications do not disappear after turning on the game.

##### Actual behavior
After the game is opened, all title bars disappear. Reloading the KDE environment via command line does nothing. You have to log out and back in to fix the issue.

##### Steps to reproduce actual behavior
1. Turn on the game
2. Close the game

**Comment by tobbi** [comment] 2018-04-17 21:41
@maxteufel I presume that this issue might not be caused by SuperTux itself. If anything, we should ask the Fedora / KDE guys to confirm, do you agree?

**Comment by maxteufel** [comment] 2018-04-18 13:09
I would definitely report this to the Fedora folks (first). Let them check that issue. (Also, windows do sound SDL-related.)

@knuxfanwin8 Can you please report this issue to the Fedora folks using whatever is the Fedora bug report procedure? Then please post a link to your report to them here.

**Comment by knuxfanwin8** [comment] 2018-04-18 13:58
I sent a bug report into the Red Hat Linux/Fedora Bugzilla specifying Supertux as the component: https://bugzilla.redhat.com/show_bug.cgi?id=1569016

**Comment by tobbi** [comment] 2018-11-30 23:05
Since this was closed as EOL, I'm gonna close the issue on our repo as well. Please open another issue on the redhat bugzilla should you still experience problems.

**Closed by tobbi** 2018-11-30 23:05 UTC
Labels: os:linux, status:needs-confirmation
