### ISSUE TITLE
Possibility to get out of the normal range in the yeti end level

### ISSUE THREAD

**Issue by Lulu-Games** [SuperTux/supertux#2750] opened 2024-01-26 15:58 UTC
Isn't that away to cheat? 
[Supertux-is-that-a-way-to-cheat.webm](https://github.com/SuperTux/supertux/assets/128484007/ecbb7f94-6eab-4a1d-a9ee-ad6fcd75b25f)

**Comment by bruhmoent** [comment] 2024-01-26 16:00
This has been known for years upon years.

**Comment by Lulu-Games** [comment] 2024-01-26 16:02
Ok

**Comment by Vankata453** [comment] 2024-01-26 16:07
Duplicate of #2489.

**Closed** 2024-01-26 16:07 UTC
