### ISSUE TITLE
Frozen snails able to be picked up and acting glitchy

### ISSUE THREAD

**Issue by Vankata453** [SuperTux/supertux#2165] opened 2022-03-12 10:57 UTC
**SuperTux version:** 0.6.3
**System information:** Windows 10

##### Expected behavior
Frozen snails aren't able to be picked up.

##### Actual behavior
Pressing Alt and still holding it after the snail is frozen allows the player to pick it up. From there, the snail starts acting pretty glitchy, appearing as a normal snail, but freezing on wall collision.

##### Steps to reproduce actual behavior
Press and hold Alt near a snail. Make sure the ice ball dodges into a wall and freezes the snail. While still holding Alt, go near the snail. There is a good chance the snail will get picked up by Tux. Try throwing it at a wall after that.

##### Additional debugging information

https://user-images.githubusercontent.com/78196474/158015264-c95437df-2439-444f-a508-2933555c20f0.mp4

**Comment by Semphriss** [comment] 2022-03-12 16:56
Does #1832 fix that error?

**Comment by mrkubax10** [comment] 2022-03-19 12:23
I can confirm that this issue happens in 0.6.2 too.

**Comment by CeIestiaI** [comment] 2022-04-23 23:53
reproduced.

**Comment by mrkubax10** [comment] 2022-12-01 19:37
Looks like it's fixed now

**Closed by mrkubax10** 2022-12-01 19:37 UTC
Labels: type:bug, category:code
