### ISSUE TITLE
Invisible walls no longer work

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#459] opened 2016-06-26 09:07 UTC
Don't start at me for this.

Where there is one of those black invisible wall objects, Tux now falls straight through them.

**Comment by maxteufel** [comment] 2016-06-26 09:33
Can't reproduce this. Test level?

**Comment by brmbrmcar** [comment] 2016-06-26 09:52
I've got http://paste.ubuntu.com/17900884/. With some of my other levels, Tux and other objects just fall through.

**Comment by maxteufel** [comment] 2016-06-26 09:54
What revision are you using?

**Comment by brmbrmcar** [comment] 2016-06-26 10:24
718 in the Nightlies 32 bit in Wine.

**Comment by maxteufel** [comment] 2016-06-26 10:34
@brmbrmcar can you reproduce it with the current nightlies (729)?

I can't, even, with your test level.

**Comment by brmbrmcar** [comment] 2016-06-26 10:55
OK, I'll try later.

**Comment by brmbrmcar** [comment] 2016-06-26 11:16
The bug still occurs.

**Comment by Hume2** [comment] 2016-06-26 11:26
I can't reproduce this as well.

**Comment by brmbrmcar** [comment] 2016-06-26 11:37
It is reproducible with http://paste.ubuntu.com/17904494/?

**Comment by maxteufel** [comment] 2016-06-26 11:41
It works as expected.

**Comment by brmbrmcar** [comment] 2016-06-26 11:43
OK. For me everything falls, the same with the older build, but not 0.4.0.

**Comment by tobbi** [comment] 2016-06-26 11:44
Screencast this, please.

**Comment by brmbrmcar** [comment] 2016-06-26 11:54
https://www.youtube.com/watch?v=vEimMYkGblI

**Comment by qwertychouskie** [comment] 2016-07-07 00:17
Maybe it is a Windows-only bug?  Or maybe a Wine bug?

**Comment by brmbrmcar** [comment] 2016-07-07 07:04
It doesn't happen  for me any more. I till think it is valid, though.

**Comment by tobbi** [comment] 2016-07-07 08:10
If it doesn't happen anymore, what makes you say it is still valid?

**Comment by brmbrmcar** [comment] 2016-07-07 14:34
Because it could still occur, and it seemed random as only I could reproduce it.

**Comment by tobbi** [comment] 2016-07-12 15:28
Can we decide on closing the issue and you can reopen it (or tell us here) if it still occurs?

**Closed by tobbi** 2016-07-12 15:28 UTC
Labels: involves:functionality, priority:high, status:needs-information, type:bug
