### ISSUE TITLE
"double iconv" causes cmake to always fail on systems that have iconv

### ISSUE THREAD

**Issue by yurivict** [SuperTux/supertux#282] opened 2015-12-21 19:00 UTC
Found in:
cmake/ConfigureChecks.cmake
external/tinygettext/CMakeLists.txt

**Comment by maxteufel** [comment] 2015-12-21 19:04
Can you pastebin a full build log until the step where it fails and share the URL here?

**Comment by yurivict** [comment] 2015-12-21 19:09
http://pastebin.com/FjEsnZ6T

**Comment by maxteufel** [comment] 2015-12-21 19:19
This is FreeBSD, right?

**Comment by yurivict** [comment] 2015-12-21 19:22
yes

**Comment by yurivict** [comment] 2015-12-21 19:22
Trying to revive supertux port there

**Comment by maxteufel** [comment] 2015-12-21 19:23
This issue doesn't appear on glibc/Linux, which has a built-in implementation of iconv (source: https://en.wikipedia.org/wiki/Iconv#History).

**Comment by maths22** [comment] 2015-12-22 01:22
I think I see what the issue is.  I'll think about what we can do about it to address it.

**Comment by snadge** [comment] 2015-12-22 12:35
I had to compile libiconv from source on Ubuntu 15.10, as per the instructions found here:
http://forum.freegamedev.net/viewtopic.php?f=67&t=5970

Not sure what to suggest other than Ubuntu's built in iconv.h causes above mentioned compile failure.

**Comment by snadge** [comment] 2015-12-24 08:46
Hmm.  It seems it may be distribution upgrade related.  I uninstalled source compiled version of libiconv, then "sudo apt-get --reinstall install libc6-dev"
It now compiles and works as expected with default iconv.

**Comment by yurivict** [comment] 2015-12-29 01:53
iconv function never returns 'double'. See here: http://man7.org/linux/man-pages/man3/iconv.3.html

You just need to find the working cmake test for iconv from some other project.

**Comment by leper** [comment] 2016-01-10 19:37
Specify `USES=iconv` in the port Makefile. See section 6.23 of the Porter's Handbook.

**Comment by maxteufel** [comment] 2016-01-22 10:33
```
[2016/01/20 18:15:35] <leper`> btw #282 seems fixed since there is https://svnweb.freebsd.org/ports/head/games/supertux2/ now (which doesn't patch around anything like that, a revision seems to make it use the SDL iconv detection in tinygettext now)
```

@yurivict can you confirm this? If so, please close this. Thanks.

**Closed** 2016-06-23 20:03 UTC
Labels: status:needs-information, type:bug
