### ISSUE TITLE
checkpoint doesn't save enemy and coin progress

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1044] opened 2019-01-13 13:14 UTC
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
If you respawn at checkpoint all coins and enemies you collected up to this point should be retained.

##### Actual behavior
They aren't, so when you restart from checkpoint 100% level completion becomes next to impossible (heavy backtracking).

##### Steps to reproduce actual behavior
Collect some coins and/or kill some foes, then activate a checkpoint, then die, and backtrack to the "collected" coins or foes.

**Comment by Rusty-Box** [comment] 2019-02-06 05:12
I think it is the same there as it is right now. As far as I know, most games are handling it this way.

**Comment by Rusty-Box** [comment] 2019-11-15 21:21
As this apoears to be intended behavior plus it makes completing levels with all coins gathered and badguys defeated more challenging I will close this for now.
In case someone disagrees this issue can be reopend if neccessary.

**Closed by Rusty-Box** 2019-11-15 21:21 UTC
Labels: category:code, category:levels, status:needs-discussion
