### ISSUE TITLE
Idea: Rocks can interact with trampolines

### ISSUE THREAD

**Issue by SalomonDFanSuperTux** [SuperTux/supertux#2148] opened 2022-02-13 14:13 UTC
SuperTux Version: 0.6.3

According to the physics of the game, a rock can't interact with trampoline, but to be honest, i think that a thing that can add to the game is the rock can interact with trampolines.
But it depends if the rock is so heavy or is lightweight, so i had another idea to add to the rock that is a option that says if the rock is heavy or not. (Obviously Tux can wear the rock if is heavy or lightweight)

Here is a little video how looks this physical or this mechanic. (sorry for the lag on video)
https://drive.google.com/file/d/1D8GnlApDNR3naFdVjVod0D4jRHCjaCCy/view?usp=sharing

**Comment by mrkubax10** [comment] 2022-02-13 16:18
Duplicate of #1321

**Closed by mrkubax10** 2022-02-13 16:18 UTC
