### ISSUE TITLE
Igloo becomes invisible when Tux is a couple of tiles below it

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#317] opened 2015-12-31 15:17 UTC
Seen in version 0.4.0:
If Tux is lower than an igloo, the igloo turns invisible. As Tux approaches closer to the igloo, it becomes visible again. I did not have to use the scrolling feature to notice it, but with the scrolling feature it becomes more obvious, of course.
My screen has a resolution of 1920×1080 (but I played in a maximized window which was slightly smaller).

I have seen this in the custom world “The Ice Continent”, level “Always Higher”. Tux has to climb upwards a lot and an igloo is located at the top, so Tux has to approach the igloo from below. That's how I noticed the problem.

**Comment by Hume2** [comment] 2016-01-01 14:43
Possible sollution: Always put decals instead of these tiles. The igloo tiles will be still there, but will work like decals on fixed z-pos.
@tobbi If you understand this mechanism, may I apply this sollution?

**Comment by Karkus476** [comment] 2016-01-01 19:28
@Hume2 But why is the issue occurring anyway? It should be a decal, yes, but that is a workaround, not a solution.

**Comment by Hume2** [comment] 2016-01-01 19:33
The issue is happening because only the on-screen tile render, so the top-left 32×32px of the igloo must be on-screen to render it. Decals have their own dimensions, so the on-screen calculations can run properly.

**Comment by Karkus476** [comment] 2016-01-02 17:14
Bugfix -> 0.4.1

**Comment by Hume2** [comment] 2016-01-03 17:48
Now I realize that it can't solve the problem, because the igloo usually isn't on solid tilemap. It needs something else.

**Comment by LMH0013** [comment] 2016-01-05 18:10
Using decals works just fine, but another potential fix is to split up each igloo tile into multiple tiles so that they behave like all other tiles.  This might be ideal because I think the current tiles are a relic from the days when there was no vertical scrolling and all levels progressed left to right.  Regardless of how it is done, the fix requires changing each level affected individually unfortunately.

**Comment by tobbi** [comment] 2016-02-07 21:41
Unfortunately, I had to revert the above since it caused assertion failures.

**Comment by Grumbel** [comment] 2018-08-01 08:34
This should be fixed by decals, not by making the tile code more complicated. The tiles larger than 32x32 was a quick ugly hack from the 0.1.x days, absolutely no need to keep that one alive.

**Closed** 2018-08-01 10:43 UTC
Labels: category:code, involves:functionality, priority:medium, type:bug
