### ISSUE TITLE
Intel Integrated Graphics Causes Problems

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#256] opened 2015-12-07 23:34 UTC
If you minimise, you get a blank screen permanently
Something to do with OpenGL.
Since it works fine on Linux, I am convinced there will be a workaround.
The tradeoff:
video = "auto" -> No minimising
video = "sdl" -> bad graphics

**Comment by tobbi** [comment] 2015-12-08 09:36
The cause *could* be a bug in the SDL library. One that might have been fixed with the most recent revision. Can you try compiling the latest sdl source code, build a DLL from it and use that instead of the packaged one?

**Comment by Karkus476** [comment] 2015-12-09 16:43
Note: This is now being considered a wontfix. If you have this problem, we have decided that unless further information becomes available, we will not (can not) fix this bug. If you have this problem, go to your SuperTux folder, open config, and change 'video' from auto to sdl. This will decrease the graphical quality, but allow you to play the game and minimise it. Another option is to switch to Linux, of course

**Comment by symvizan** [comment] 2015-12-15 12:32
Intel graphics has problems almost with all games.

**Comment by sydneyjd** [comment] 2015-12-15 14:54
It does matter on the Intel chipset. I don't have the issue with my intel card.

**Closed** 2016-04-14 21:05 UTC
Labels: os:windows, type:bug, wontfix
