### ISSUE TITLE
Issue After Installing Add-on

### ISSUE THREAD

**Issue by marc280492** [SuperTux/supertux#110] opened 2015-08-14 21:07 UTC
After installing a world map, the home screen is me becomes: 
![captura1](https://cloud.githubusercontent.com/assets/11487343/9284050/e015e2fc-42d8-11e5-885f-1ee2e645ba07.PNG)

**Comment by tobbi** [comment] 2015-08-14 21:11
Which world map did you install?

**Comment by maceleiro** [comment] 2015-08-14 21:11
@tobbi Yeti's revenge

**Comment by tobbi** [comment] 2015-08-14 21:29
Please chat with us at http://supertux.github.io/contact.html and let's see if we can resolve the problem.

**Comment by maceleiro** [comment] 2015-08-16 13:09
@tobbi This problem happens after I get off any world map

**Comment by maceleiro** [comment] 2015-08-16 21:30
Any news @tobbi?

**Comment by maceleiro** [comment] 2015-08-16 21:32
Installing Levels of wolfs, I have not had the same problem. The main menu has worked for me. But I would very slow animations (including the video leaving background, Tux is very slow)

**Comment by maceleiro** [comment] 2015-08-17 13:11
In the mobile format I not have this problem. I think that only happens in certain circumstances. I have a ASUS R510J with Windows 10. Please put the issue label.

**Comment by Karkus476** [comment] 2015-09-08 11:14
It's difficult to know what to do unless this is reproducible. I haven't had this problem, but if you think this is something that needs fixing at this end, you need a set of instructions for us to get the same bug.

**Comment by tobbi** [comment] 2015-09-18 22:40
I have actually never experienced this problem. No idea what might be causing this or whether it's something we can fix.

**Comment by Karkus476** [comment] 2015-09-24 21:22
@maceleiro  Try removing the addon and trying again maybe?

**Comment by sydneyjd** [comment] 2015-09-30 21:18
Something sounds corrupt.
@maceleiro Does it still do this?
If you don't respond in the next week i will just go ahead and close this issue.

**Comment by maceleiro** [comment] 2015-10-03 06:49
Even I have the same problem...

**Comment by tobbi** [comment] 2015-10-03 08:05
Can you give us a copy of your supertux profile folder?

**Comment by maceleiro** [comment] 2015-10-03 09:41
@tobbi Where is this folder...? :smile:

**Comment by tobbi** [comment] 2015-10-03 09:42
In .supertux in your home directory, if I recall correctly.

**Comment by maceleiro** [comment] 2015-10-03 09:45
Thanks!! https://drive.google.com/file/d/0B6JsEr5ZVJgPZzB1UkJiVTRWWkE/view?usp=sharing

**Comment by tobbi** [comment] 2015-10-05 23:06
Unfortunately, I cannot reproduce the issue here. I loaded your configuration files, and it displayed fine for me.

**Comment by tobbi** [comment] 2015-10-08 17:34
By the way: Do things change if you start it with ./supertux2 --renderer sdl vs ./supertux2 --renderer opengl?

**Comment by Karkus476** [comment] 2015-11-05 17:16
Requesting close

**Comment by tobbi** [comment] 2015-11-05 18:42
Please re-open if this issue occurs again.

**Closed by tobbi** 2015-11-05 18:42 UTC
Labels: category:code, status:needs-information
