### ISSUE TITLE
Animations loop if you pause and then unpause game

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#165] opened 2015-09-29 18:41 UTC
Rarely when i pause and then unpause the game, some animations like Tux growing and Mr Bomb exploding loop endlessly.

**Comment by brmbrmcar** [comment] 2015-09-29 20:22
Can't reproduce that.

**Comment by tobbi** [comment] 2015-09-30 10:11
Are we talking about the sounds?

**Comment by Savsish** [comment] 2015-09-30 11:01
I know it's very hard to reproduce but pause the game during the last frame of Tux growing or Mr Bomb exploding and then unpause the game, the animation loops endlessly. This especially problematically with Mr Bomb as it won't explode or the explosion lasts forever until you restart the level.

**Comment by sydneyjd** [comment] 2015-09-30 11:59
@Savsish Can you take a video of the game when it does this? Also, can you run supertux with '--debug' and see if it tells you anything about it?

**Comment by Savsish** [comment] 2015-09-30 12:04
I have recorded this glitch with Fraps, but unfortunately i don't have the video anymore.

**Comment by brmbrmcar** [comment] 2015-09-30 14:41
Oh yes, I've got it now.

**Comment by sydneyjd** [comment] 2015-09-30 14:51
Well, can someone *PLEASE* Get a video of it?

**Comment by brmbrmcar** [comment] 2015-09-30 14:53
If I can get screencast to work on my Chromebook...

**Comment by brmbrmcar** [comment] 2015-10-02 17:27
It's not going  to work...

**Comment by Hume2** [comment] 2015-10-10 12:43
I can't reproduce it.

**Comment by sydneyjd** [comment] 2015-10-27 17:25
No one else can reproduce it? If you can, you can re-open this issue, otherwise im going to close it.

**Comment by brmbrmcar** [comment] 2015-10-27 17:26
I can, but can't screen record.

**Comment by sydneyjd** [comment] 2015-10-27 17:26
Yes, you, but i need someone else beside you.

**Comment by Karkus476** [comment] 2015-10-27 18:09
@brmbrmcar why can't you screen record?

**Comment by Karkus476** [comment] 2015-10-27 18:10
@sydneyjd I'm not going to undo your closing, but unless this is open, it is not going to get the attention it may well need, it's had a warning, so give it a few days before closing it. Please?

**Comment by brmbrmcar** [comment] 2015-10-27 18:12
I am using crouton.

**Comment by Karkus476** [comment] 2015-10-27 18:14
@brmbrmcar Oh. Okay

**Comment by brmbrmcar** [comment] 2015-10-27 18:14
I hope they fix it.

**Comment by sydneyjd** [comment] 2015-10-27 23:25
Fine. :-)

**Comment by Karkus476** [comment] 2015-11-22 00:53
I cannot seem to reproduce this. @brmbrmcar and @Savsish , a video will *really* help this bug to be fixed, as well as providing solid evidence. Until then, this will not be fixed as no person willing to do the fix can replicate the bug.

**Comment by brmbrmcar** [comment] 2015-11-22 09:15
How should I video it?

**Comment by MCMic** [comment] 2016-01-07 12:34
@brmbrmcar if you run GNU/Linux you can use «ffmpeg -f x11grab -show_region 1 -video_size xga -i :0.0 out.mp4» or something like that to get ffmpeg to record a screen region into the file out.mp4

**Comment by brmbrmcar** [comment] 2016-01-07 15:39
I don't understand that. It probably would even work on my Chromebook anyway. Anyone know how the Supertux --record-demo function works?

**Comment by maxteufel** [comment] 2016-01-07 15:41
@brmbrmcar you use `supertux2 --record-demo demo-file path/to/level/file` which creates `demo-file`, containing the actions you did while playing. `supertux2 --play-demo demo-file path/to/level/file` can then be used to replay the level.

**Comment by brmbrmcar** [comment] 2016-01-07 16:42
What file type does the output have to be? That is where I am unsure. MP4 didn't work.

**Comment by maxteufel** [comment] 2016-01-07 18:03
@brmbrmcar just a .txt - it won't record a video, just your actions.

**Comment by Karkus476** [comment] 2016-01-07 19:06
@brmbrmcar As in, the buttons you press (before you ask for clarification)

**Comment by brmbrmcar** [comment] 2016-01-07 19:35
OK, not as good as I thought.

**Comment by brmbrmcar** [comment] 2016-02-07 11:59
http://www.fileconvoy.com/gf.php?id=gb217fb7e37a2c6d8999784687.837149d7cb8ce022c88166&sts=1454846302213122145223331990d10d62362d940986d4ae166d10 I got it working!

**Comment by maxteufel** [comment] 2016-10-22 16:53
Please reopen if you can still reproduce it.

**Closed by maxteufel** 2016-10-22 16:53 UTC
Labels: category:code, priority:medium, status:needs-information, type:bug
