### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by basxto** [SuperTux/supertux#2082] opened 2022-01-13 03:31 UTC
Adding some achievements could be neat. It would probably a good idea to do this per world, so that addons can add their own.

Ideally with steam integration (for the story world), see [steamshim](https://github.com/icculus/steamshim) for using the Steamworks SDK with GPL games.

This is a feature request based on https://steamcommunity.com/app/1572920/discussions/0/3193614254329940613/

**Comment by Semphriss** [comment] 2022-01-13 03:32
Duplicate of #2044 which has been moved to #2064

**Closed by Semphriss** 2022-01-13 03:32 UTC
