### ISSUE TITLE
.dmg for .6.1 doesn't open properly

### ISSUE THREAD

**Issue by deja-geek** [SuperTux/supertux#1278] opened 2019-12-15 23:52 UTC
**SuperTux version:*0.6.1*
**System information:** *(details about your kernel, operating system, or distribution)*
MacOS Mojave
##### Expected behavior
Mount .dmg
##### Actual behavior
.dmg doesn't mount.  System hangs slightly but never opens.
##### Steps to reproduce actual behavior
Attempt to mount .dmg
##### Additional debugging information
I've downloaded 0.6.1 .dmg multiple times, using different browsers.  Still same issue.  .0.6.0 .dmg mounts just fine.
*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

**Comment by tobbi** [comment] 2019-12-15 23:59
I can't reproduce the issue on my machine (which is Mac OS X High Sierra, however). I'll have to get someone with Mojave to test it.

**Comment by tobbi** [comment] 2020-04-13 11:56
Does the problem persist with this file? https://supertux-ci-downloads.s3-us-west-2.amazonaws.com/99f72fba3d7694e3d108f972e18053059e0fd78d/travis/osx/318647934/SuperTux--128-NOTFOUND-Darwin.dmg

**Comment by deja-geek** [comment] 2020-04-13 22:11
That .dmg mounts without any issues

**Comment by tobbi** [comment] 2021-12-27 23:21
I'm assuming that the current release of 0.6.3 also works without any issues: 
https://github.com/SuperTux/supertux/releases/tag/v0.6.3

I'm gonna close the issue. Should it appear again, feel free to re-open.

**Closed by tobbi** 2021-12-27 23:21 UTC
Labels: category:code, status:needs-confirmation
