### ISSUE TITLE
SuperTux quits immediately

### ISSUE THREAD

**Issue by jumpball** [SuperTux/supertux#408] opened 2016-05-03 07:30 UTC
**SuperTux version: 0.4.0.372**
**System information:**
Operating system: Mac OS X 10.6.8
Processor: 2 GHz Intel Core 2 Duo
##### Expected and actual behavior
I downloaded SuperTux-0.4.0.372-Darwin.dmg and opened this file. Then I opened SuperTux.app from this disk image and expected SuperTux.app to open. But it quits immediately, even when I try again.
##### Steps to reproduce actual behavior
OS X's crash reporter outputs this, when SuperTux.app quitted:
Process:         sh [305]
Path:            /Volumes/SuperTux 0.4.0-372-gebd3182/SuperTux.app/Contents/MacOS/SuperTux
Identifier:      com.googlecode.supertux2
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [106]
Date/Time:       2016-05-03 08:36:50.432 +0200
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6
Interval Since Last Report:          157926 sec
Crashes Since Last Report:           1
Per-App Crashes Since Last Report:   1
Anonymous UUID:                      FD65F1DF-5ACA-4C95-BB95-59CF1EFEA101
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Crashed Thread:  Unknown
Backtrace not available
Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0xfffffffffffffff8
Binary images description not available
Model: Macmini2,1, BootROM MM21.009A.B00, 2 processors, Intel Core 2 Duo, 2 GHz, 1 GB, SMC 1.19f2
Graphics: Intel GMA 950, GMA 950, Built-In, spdisplays_integrated_vram
Memory Module: global_name
_(Bluetooth, Network Service, Airport — nothing important)_
Serial ATA Device: Hitachi HTS541612J9SA00, 111.79 GB
Parallel ATA Device: PIONEER DVD-RW  DVR-K06
_(..., there is lots of information about USB devices, it isn't important for this problem)_

**Comment by tobbi** [comment] 2016-05-03 10:53
Duplicate of #284?

**Comment by tobbi** [comment] 2016-05-03 20:02
Does SuperTux start when you try it from the terminal (move SuperTux.app to Applications first).
/Applications/SuperTux.app/Contents/MacOS/SuperTux

**Comment by jumpball** [comment] 2016-06-04 13:14
@tobbi No, it does not start in Applications from Terminal (Segmentation fault).

**Comment by tobbi** [comment] 2016-06-04 17:07
Do you know how to use a debugger? If you could get me a stacktrace, that would be nice.

**Comment by maxteufel** [comment] 2016-10-22 16:50
Please reopen if you can reproduce it.

**Closed by maxteufel** 2016-10-22 16:50 UTC
Labels: os:macos, status:needs-information
