### ISSUE TITLE
The backgrounds of some levels and the main menu is glitched

### ISSUE THREAD

**Issue by diablo488** [SuperTux/supertux#2332] opened 2022-11-14 09:34 UTC
**SuperTux version:*SuperTux-v0.6.3-645-g76833f0c8-win64*
**System information:*Windows 10 Pro, intel HD4000 igpu*

The backgrounds of some levels and the main menu is glitched everytime i play this version
i have included my config file just in case

![Screenshot (241)](https://user-images.githubusercontent.com/54474885/201624286-b769c1ac-7284-4dbe-9313-021cc35997d9.png)
![Screenshot (248)](https://user-images.githubusercontent.com/54474885/201624297-56c493cf-6778-4625-88e0-df201c1ac0ff.png)
[config.txt](https://github.com/SuperTux/supertux/files/10001581/config.txt)

**Comment by Vankata453** [comment] 2022-11-14 09:41
Duplicate of #2306.

**Comment by serano01** [comment] 2022-11-14 13:06
> Duplicate of #2306.

Indeed. Closing.

**Closed by serano01** 2022-11-14 13:06 UTC
