### ISSUE TITLE
An Editor Guide

### ISSUE THREAD

**Issue by LizzyBach** [SuperTux/supertux#2244] opened 2022-07-11 13:31 UTC
I'm not sure if it exists or not but I think it'd be a great idea to make a guide for the level editor. Don't get me wrong, the editor is pretty intuitive when it comes to simple stuff. But more complicated things, especially the things that require scripts, can be pretty intimidating. I think making an 'official editor guide' for things like how to get a switch to start moving a platform or how to fade a tilemap would be really appreciated.

Btw I searched for a guide and I found one but it seemed to not be working. I know that there are videos about the editor but they're not necessarily ideal. An official editor guide would make a great addition and it'd be even better if it could be accessed through the game. What do you think?

**Comment by Vankata453** [comment] 2022-07-11 15:08
Duplicate of #505. An editor guide is currently being worked on, you can check the [following pull request](https://github.com/SuperTux/wiki/pull/30) on the SuperTux wiki repository.

**Comment by ixPost** [comment] 2022-07-11 15:19
Also, what kinds of scripts can you put into objects?

**Closed** 2022-07-11 20:46 UTC
